"""Pinned ATT&CK dataset access for the MITRE assessment module.

Loads apps/api/app/mitre/data/attack.json (generated by
scripts/build_attack_data.py, checked into the repo) once at import time.
The app never fetches ATT&CK data from the internet.

Pure stdlib; no app imports. Later phases stamp ``DEFAULT.version`` on every
assessment.
"""

import json
import re
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "data"
DOMAINS = ("enterprise", "ics", "mobile")

_TECHNIQUE_ID_RE = re.compile(r"^T\d{4}(\.\d{3})?$")


def is_valid_technique_id(value) -> bool:
    """True for well-formed ATT&CK technique IDs: T1234 or T1234.001."""
    return bool(_TECHNIQUE_ID_RE.match(value or ""))


class AttackIndex:
    """Read-only index over the compact attack.json dataset shape.

    Injectable into the pure applicability/coverage functions so tests can
    run against small synthetic datasets; production code uses ``DEFAULT``.
    """

    def __init__(self, dataset: dict):
        self.version = dataset.get("version", "unknown")
        self.domains = {}
        self.by_id = {}
        self.children = {}  # parent technique id -> [sub-technique dicts]
        for domain, dd in dataset.get("domains", {}).items():
            techniques = []
            for raw in dd.get("techniques", []):
                tech = dict(raw, domain=domain)
                techniques.append(tech)
                self.by_id[tech["id"]] = tech
                if tech.get("parent_id"):
                    self.children.setdefault(tech["parent_id"], []).append(tech)
            self.domains[domain] = {
                "tactics": dd.get("tactics", []),
                "techniques": techniques,
            }

    def get(self, technique_id):
        return self.by_id.get(technique_id)

    def tactics(self, domain):
        return self.domains.get(domain, {}).get("tactics", [])

    def techniques(self, domain=None):
        if domain is not None:
            return self.domains.get(domain, {}).get("techniques", [])
        return [t for dd in self.domains.values() for t in dd["techniques"]]

    def resolve(self, technique_id):
        """Validate + canonicalize a technique ID.

        Returns ``(canonical_id, status)`` where status is one of:
        - ``ok``: valid, active technique.
        - ``remapped``: revoked ID followed to its ``superseded_by`` successor.
        - ``deprecated``: resolves to a technique deprecated in this release.
        - ``unknown``: well-formed but not in the dataset (or revoked with no
          live successor — MITRE ships one such orphan, mobile T1454).
        - ``malformed``: does not match T1234 / T1234.001.
        canonical_id is None for unknown/malformed.
        """
        if not is_valid_technique_id(technique_id):
            return None, "malformed"
        tech = self.by_id.get(technique_id)
        if tech is None:
            return None, "unknown"
        remapped, hops = False, 0
        while tech.get("revoked"):
            successor = tech.get("superseded_by")
            if not successor or successor not in self.by_id or hops >= 5:
                return None, "unknown"
            tech = self.by_id[successor]
            remapped, hops = True, hops + 1
        if tech.get("deprecated"):
            return tech["id"], "deprecated"
        return tech["id"], ("remapped" if remapped else "ok")


def load_technique_priorities() -> dict:
    """Curated priority tiers for gap ranking (used from Phase 2 onward)."""
    path = DATA_DIR / "technique_priorities.json"
    return json.loads(path.read_text(encoding="utf-8"))


DEFAULT = AttackIndex(
    json.loads((DATA_DIR / "attack.json").read_text(encoding="utf-8"))
)
