"""Ingest tests for the Code Security Review module (pure, no DB/LLM).

Uses the deterministic sample generated by
scripts/generate_codereview_sample.py (regenerate via that script if the
fixture shape ever changes).
"""

import json
from pathlib import Path

import pytest

from app.codereview import ingest
from app.codereview.ingest import IngestError

SAMPLE_DIR = Path(__file__).resolve().parents[3] / "docs/sample/CodeReview_Sample"


def _sample(name: str) -> bytes:
    return (SAMPLE_DIR / name).read_bytes()


def test_parse_findings_json_sample():
    report = ingest.parse_report(_sample("acme_findings.json"))
    assert report["source_format"] == "findings"
    assert report["counts"]["total"] == 12
    assert sum(report["counts"]["by_severity"].values()) == 12
    assert set(report["counts"]["by_severity"].keys()) == set(ingest.SEVERITIES)

    findings = report["findings"]
    assert [f["idx"] for f in findings] == list(range(1, 13))

    ranks = [ingest._SEVERITY_RANK[f["severity"]] for f in findings]
    assert ranks == sorted(ranks)

    dup_findings = [f for f in findings if f["duplicates"]]
    assert len(dup_findings) == 2

    assert len(report["chains"]) == 2
    assert report["dropped_count"] == 3


def test_parse_sarif_sample():
    report = ingest.parse_report(_sample("acme_findings.sarif"))
    assert report["source_format"] == "sarif"
    assert report["counts"]["total"] == 12
    assert sum(report["counts"]["by_severity"].values()) == 12


def test_unknown_severity_normalized_to_medium():
    raw = {
        "repo_root": "/x",
        "findings": [
            {"finding": {"title": "x", "file": "a.py"}, "severity": "weird", "exploitability_notes": ""}
        ],
    }
    import json

    report = ingest.parse_report(json.dumps(raw).encode())
    assert report["findings"][0]["severity"] == "medium"
    assert any("unknown severity" in a for a in report["assumptions"])


def test_findings_cap_at_2000():
    import json

    raw = {
        "repo_root": "/x",
        "findings": [
            {
                "finding": {"title": f"f{i}", "file": "a.py", "severity": "low"},
                "severity": "low",
                "exploitability_notes": "",
            }
            for i in range(2500)
        ],
    }
    report = ingest.parse_report(json.dumps(raw).encode())
    assert report["counts"]["total"] == 2000
    assert report["dropped_count"] == 500
    assert any("kept the first" in a for a in report["assumptions"])


def test_invalid_json_raises():
    with pytest.raises(IngestError):
        ingest.parse_report(b"{not json")


def test_unrecognized_shape_raises():
    with pytest.raises(IngestError):
        ingest.parse_report(b'{"foo": "bar"}')


def test_parse_manifest_extracts_fields():
    manifest = ingest.parse_manifest(_sample("acme_run_manifest.json"))
    assert manifest["target_git_sha"] == "3f9c2a1"
    assert manifest["total_cost_usd"] == 1.94


def test_chain_steps_remap_to_sorted_idx():
    """Chain steps index VVAH's original order; after severity sort they must
    point at the renumbered display idx (1-based input here)."""
    obj = {
        "repo_root": "/r", "summary": "", "raw_findings_count": 2,
        "findings": [
            {"finding": {"title": "low one", "file": "a.py", "line_start": 1,
                         "vuln_class": "other"}, "severity": "low", "exploitability_notes": ""},
            {"finding": {"title": "crit one", "file": "b.py", "line_start": 1,
                         "vuln_class": "injection"}, "severity": "critical", "exploitability_notes": ""},
        ],
        "chains": [{"title": "c", "steps": [2, 1], "severity": "high", "narrative": "n"}],
    }
    report = ingest.parse_report(json.dumps(obj).encode())
    assert [f["title"] for f in report["findings"]] == ["crit one", "low one"]
    assert report["chains"][0]["steps"] == [1, 2]
    assert "_pos" not in report["findings"][0]


REAL_DIR = SAMPLE_DIR / "real" / "nodegoat"


def test_real_nodegoat_golden():
    """Golden: a real VVAH 1.3.0 run (OWASP/NodeGoat) parses with the facts
    recorded in real/nodegoat/README.md. Breaks first if a VVAH bump changes
    the FinalReport schema."""
    report = ingest.parse_report((REAL_DIR / "findings.json").read_bytes())
    assert report["source_format"] == "findings"
    assert report["counts"]["total"] == 29
    assert report["counts"]["by_severity"] == {"critical": 6, "high": 5, "medium": 18, "low": 0, "info": 0}
    assert report["raw_findings_count"] == 88 and report["dropped_count"] == 59
    assert len(report["chains"]) == 6
    assert report["assumptions"] == []
    assert report["git_sha"] == "c5cb68a7084e4ae7dcc60e6a98768720a81841e8"
    n = report["counts"]["total"]
    for f in report["findings"]:
        assert f["file"] and f["title"] and f["cwe"] and f["cvss_score"] is not None
        assert f["vuln_class_label"]  # real output has null labels -> fallback to class id
        assert f["verdict"] == "TRUE_POSITIVE"
    for c in report["chains"]:
        assert c["steps"] and all(1 <= s <= n for s in c["steps"])

    sarif = ingest.parse_report((REAL_DIR / "nodegoat_report.sarif").read_bytes())
    assert sarif["source_format"] == "sarif" and sarif["counts"]["total"] == 29
    assert sarif["counts"]["by_severity"] == report["counts"]["by_severity"]

    manifest = ingest.parse_manifest((REAL_DIR / "run_manifest_20260911T185822Z.json").read_bytes())
    assert manifest["tool_version"] == "1.3.0"
    assert manifest["total_tokens"] == 3400424 and manifest["total_cost_usd"] is None
    assert manifest["models"]["deepdive"]["id"] == "deepseek/deepseek-v4-pro"
