"""Ingest tests for the Code Security Review module (pure, no DB/LLM).

Uses the deterministic sample generated by
scripts/generate_codereview_sample.py (regenerate via that script if the
fixture shape ever changes).
"""

import json
from pathlib import Path

import pytest

from app.codereview import ingest
from app.codereview.ingest import IngestError

SAMPLE_DIR = Path(__file__).resolve().parents[3] / "docs/sample/CodeReview_Sample"


def _sample(name: str) -> bytes:
    return (SAMPLE_DIR / name).read_bytes()


# VVAH 1.3.0 FinalReport/Finding field lists, from vvaharness/models/_scan.py
# (see docs/sample/CodeReview_Sample/acme_full_schema.json and its generator,
# scripts/generate_codereview_sample.py, for the fixture pinned against these).
# A VVAH version bump that adds/renames a field must update this list
# consciously — that's the point of test_real_fixture_uses_only_known_fields.
FINAL_REPORT_FIELDS_1_3_0 = [
    "repo_root", "repo_name", "git_sha", "findings", "chains", "dropped",
    "raw_findings_count", "metrics", "threat_model", "app_profile",
    "unreachable_files", "summary", "degraded", "degraded_reason",
]
FINDING_FIELDS_1_3_0 = [
    "title", "file", "line_start", "vuln_class", "severity", "line_end",
    "cwe", "vuln_class_label", "chunk_id", "impact", "description",
    "exploit_scenario", "preconditions", "recommendation", "code_snippet",
    "source_ref", "sink_ref", "confidence", "votes", "duplicates",
    "backfilled_refs", "case_id", "exploitability_notes", "verdict",
    "verdict_confidence", "verdict_reason", "cvss_vector", "cvss_score",
    "cvss_rating", "verifier_reasoning", "vsvs_vector", "vsvs_score",
    "vsvs_rating", "offensive_priority", "offensive_reason",
]

FULL_SCHEMA_FILE = "acme_full_schema.json"


def test_full_schema_fixture_populates_every_field():
    obj = json.loads(_sample(FULL_SCHEMA_FILE))

    for field in FINAL_REPORT_FIELDS_1_3_0:
        assert field in obj, f"FinalReport field {field!r} missing from fixture"

    findings = obj["findings"]
    assert findings, "fixture must have at least one finding"
    for entry in findings:
        finding = entry["finding"]
        for field in FINDING_FIELDS_1_3_0:
            assert field in finding, f"Finding field {field!r} missing on {finding.get('title')!r}"

    # every field is non-empty on at least one finding
    for field in FINDING_FIELDS_1_3_0:
        assert any(finding["finding"].get(field) not in (None, "", [], {}) for finding in findings), (
            f"Finding field {field!r} is empty/null on every finding in the fixture"
        )


def test_full_schema_ingest_keeps_contract_fields():
    report = ingest.parse_report(_sample(FULL_SCHEMA_FILE))

    assert report["counts"]["total"] == 8
    assert sum(report["counts"]["by_severity"].values()) == 8
    n = report["counts"]["total"]
    for chain in report["chains"]:
        assert chain["steps"] and all(1 <= s <= n for s in chain["steps"])
    assert report["dropped_count"] == 6

    assert report["degraded"] is True
    assert report["degraded_reason"]

    metrics = report["metrics"]
    for key in (
        "duration_sec", "total_files_in_scope", "analyzed_files_unique",
        "loc_scanned_by_language", "true_positive_count",
        "false_positive_count", "total_tokens",
    ):
        assert metrics.get(key) is not None

    contract_fields = (
        "source_ref", "sink_ref", "verdict", "verdict_confidence",
        "verdict_reason", "offensive_priority", "offensive_reason",
        "exploitability_notes", "verifier_reasoning", "cvss_vector",
        "cvss_score", "cvss_rating", "preconditions", "duplicates",
    )
    first = report["findings"][0]
    for field in contract_fields:
        assert first.get(field) not in (None, "", [], {}), f"contract field {field!r} not carried through"


def test_real_fixture_uses_only_known_fields():
    """Proves the pinned field lists match reality: every key VVAH's own real
    NodeGoat golden output actually uses is one we know about. If VVAH adds a
    field this fails and FINDING_FIELDS_1_3_0 / FINAL_REPORT_FIELDS_1_3_0 must
    be bumped consciously."""
    obj = json.loads((SAMPLE_DIR / "real" / "nodegoat" / "findings.json").read_bytes())

    unknown_top = set(obj.keys()) - set(FINAL_REPORT_FIELDS_1_3_0)
    assert not unknown_top, f"unknown FinalReport fields in real fixture: {unknown_top}"

    for entry in obj["findings"]:
        unknown = set(entry["finding"].keys()) - set(FINDING_FIELDS_1_3_0)
        assert not unknown, f"unknown Finding fields in real fixture: {unknown}"


def test_parse_findings_json_sample():
    report = ingest.parse_report(_sample("acme_findings.json"))
    assert report["source_format"] == "findings"
    assert report["counts"]["total"] == 12
    assert sum(report["counts"]["by_severity"].values()) == 12
    assert set(report["counts"]["by_severity"].keys()) == set(ingest.SEVERITIES)

    findings = report["findings"]
    assert [f["idx"] for f in findings] == list(range(1, 13))

    ranks = [ingest._SEVERITY_RANK[f["severity"]] for f in findings]
    assert ranks == sorted(ranks)

    dup_findings = [f for f in findings if f["duplicates"]]
    assert len(dup_findings) == 2

    assert len(report["chains"]) == 2
    assert report["dropped_count"] == 3


def test_parse_sarif_sample():
    report = ingest.parse_report(_sample("acme_findings.sarif"))
    assert report["source_format"] == "sarif"
    assert report["counts"]["total"] == 12
    assert sum(report["counts"]["by_severity"].values()) == 12


def test_sarif_agentic_sast_sections_mapped():
    # Shape of Agentic SAST 1.4.0 SARIF (Keycloak run, 2026-09-17), trimmed.
    desc = (
        "*1 additional call site(s) collapsed during dedup.*\n\n"
        "#### Description\nToken is not bound to the client.\n\n"
        "#### Impact\nAccount takeover.\n\n"
        "#### Exploit scenario\nReplay a token from another client.\n\n"
        "#### Preconditions\n- Attacker has a token\n- Exchange is enabled\n\n"
        "```\nreturn exchange(token);\n```\n\n"
        "#### How to fix\nCheck the audience.\n\n"
        "**Exploitability:** Post-auth, network reachable.\n\n"
        "#### Adversarial verification\n"
        "**Verdict:** TRUE_POSITIVE (confidence: 9/10) — Confirmed reachable."
    )
    sarif = {
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {"name": "Agentic SAST", "version": "1.4.0"}},
            "properties": {"scanDegraded": True},
            "invocations": [{"toolExecutionNotifications": [
                {"message": {"text": "s4: 101 non-fatal error(s) logged"}},
                {"message": {"text": "Exploit-chain analysis could not be computed"}},
            ]}],
            "results": [{
                "ruleId": "CWE-287",
                "message": {"text": "External token exchange accepts any client's token  [CVSS 9.6: CVSS:3.1/AV:N]"},
                "locations": [{"physicalLocation": {"artifactLocation": {"uri": "a/B.java"}, "region": {"startLine": 5}}}],
                "properties": {
                    "severity": "critical", "cvssScore": 9.6, "category": "CWE-287: Improper Authentication",
                    "offensivePriority": "P3", "offensivePriorityReason": "Internal network", "description": desc,
                },
                "remediation": {"remediationStatus": "skipped", "remediationReason": "report-only run"},
            }],
        }],
    }
    report = ingest.parse_report(json.dumps(sarif).encode())
    f = report["findings"][0]
    assert f["title"] == "External token exchange accepts any client's token"
    assert f["description"] == "Token is not bound to the client."
    assert f["impact"] == "Account takeover."
    assert f["exploit_scenario"] == "Replay a token from another client."
    assert f["preconditions"] == ["Attacker has a token", "Exchange is enabled"]
    assert f["recommendation"] == "Check the audience."
    assert f["code_snippet"] == "return exchange(token);"
    assert (f["verdict"], f["verdict_confidence"], f["verdict_reason"]) == ("TRUE_POSITIVE", 9, "Confirmed reachable.")
    assert f["offensive_priority"] == "P3"
    assert f["vuln_class_label"] == "CWE-287: Improper Authentication"
    assert f["exploitability_notes"] == "Post-auth, network reachable.\n\nRemediation: skipped. report-only run"
    assert report["degraded"] is True
    assert report["degraded_reason"] == "Exploit-chain analysis could not be computed"


def test_unknown_severity_normalized_to_medium():
    raw = {
        "repo_root": "/x",
        "findings": [
            {"finding": {"title": "x", "file": "a.py"}, "severity": "weird", "exploitability_notes": ""}
        ],
    }
    import json

    report = ingest.parse_report(json.dumps(raw).encode())
    assert report["findings"][0]["severity"] == "medium"
    assert any("unknown severity" in a for a in report["assumptions"])


def test_findings_cap_at_2000():
    import json

    raw = {
        "repo_root": "/x",
        "findings": [
            {
                "finding": {"title": f"f{i}", "file": "a.py", "severity": "low"},
                "severity": "low",
                "exploitability_notes": "",
            }
            for i in range(2500)
        ],
    }
    report = ingest.parse_report(json.dumps(raw).encode())
    assert report["counts"]["total"] == 2000
    assert report["dropped_count"] == 500
    assert any("kept the first" in a for a in report["assumptions"])


def test_invalid_json_raises():
    with pytest.raises(IngestError):
        ingest.parse_report(b"{not json")


def test_unrecognized_shape_raises():
    with pytest.raises(IngestError):
        ingest.parse_report(b'{"foo": "bar"}')


def test_parse_manifest_extracts_fields():
    manifest = ingest.parse_manifest(_sample("acme_run_manifest.json"))
    assert manifest["target_git_sha"] == "3f9c2a1"
    assert manifest["total_cost_usd"] == 1.94


def test_chain_steps_remap_to_sorted_idx():
    """Chain steps index VVAH's original order; after severity sort they must
    point at the renumbered display idx (1-based input here)."""
    obj = {
        "repo_root": "/r", "summary": "", "raw_findings_count": 2,
        "findings": [
            {"finding": {"title": "low one", "file": "a.py", "line_start": 1,
                         "vuln_class": "other"}, "severity": "low", "exploitability_notes": ""},
            {"finding": {"title": "crit one", "file": "b.py", "line_start": 1,
                         "vuln_class": "injection"}, "severity": "critical", "exploitability_notes": ""},
        ],
        "chains": [{"title": "c", "steps": [2, 1], "severity": "high", "narrative": "n"}],
    }
    report = ingest.parse_report(json.dumps(obj).encode())
    assert [f["title"] for f in report["findings"]] == ["crit one", "low one"]
    assert report["chains"][0]["steps"] == [1, 2]
    assert "_pos" not in report["findings"][0]


REAL_DIR = SAMPLE_DIR / "real" / "nodegoat"


def test_real_nodegoat_golden():
    """Golden: a real VVAH 1.3.0 run (OWASP/NodeGoat) parses with the facts
    recorded in real/nodegoat/README.md. Breaks first if a VVAH bump changes
    the FinalReport schema."""
    report = ingest.parse_report((REAL_DIR / "findings.json").read_bytes())
    assert report["source_format"] == "findings"
    assert report["counts"]["total"] == 29
    assert report["counts"]["by_severity"] == {"critical": 6, "high": 5, "medium": 18, "low": 0, "info": 0}
    assert report["raw_findings_count"] == 88 and report["dropped_count"] == 59
    assert len(report["chains"]) == 6
    assert report["assumptions"] == []
    assert report["git_sha"] == "c5cb68a7084e4ae7dcc60e6a98768720a81841e8"
    n = report["counts"]["total"]
    for f in report["findings"]:
        assert f["file"] and f["title"] and f["cwe"] and f["cvss_score"] is not None
        assert f["vuln_class_label"]  # real output has null labels -> fallback to class id
        assert f["verdict"] == "TRUE_POSITIVE"
    for c in report["chains"]:
        assert c["steps"] and all(1 <= s <= n for s in c["steps"])

    sarif = ingest.parse_report((REAL_DIR / "nodegoat_report.sarif").read_bytes())
    assert sarif["source_format"] == "sarif" and sarif["counts"]["total"] == 29
    assert sarif["counts"]["by_severity"] == report["counts"]["by_severity"]

    manifest = ingest.parse_manifest((REAL_DIR / "run_manifest_20260911T185822Z.json").read_bytes())
    assert manifest["tool_version"] == "1.3.0"
    assert manifest["total_tokens"] == 3400424 and manifest["total_cost_usd"] is None
    assert manifest["models"]["deepdive"]["id"] == "deepseek/deepseek-v4-pro"
