"""
Built-in validation rules.

T-504: Create built-in rules as data structures (no database)
"""

# Bump whenever the rule set below changes -- recorded in each review's
# audit_meta (Phase D) so a stored review can be traced to the rule library
# that produced it.
RULES_VERSION = "2026-07-23.1"


def get_builtin_rules() -> list[dict]:
    """
    Return list of built-in SOW validation rules.

    Each rule is a dict with: rule_id, name, description, document_types,
    severity, check_type, params, recommendation.
    """
    return [
        # Section presence rules (T-505)
        {
            "rule_id": "SOW-001",
            "name": "Executive Summary Required",
            "description": "SOW must contain an Executive Summary or Overview section",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "section_presence",
            "params": {"required_sections": ["Executive Summary", "Overview", "Summary", "Purpose", "Introduction", "Background"]},
            "recommendation": "Add an Executive Summary section at the beginning of the document",
        },
        {
            "rule_id": "SOW-002",
            "name": "Scope of Work Section Required",
            "description": "SOW must clearly define the Scope of Work",
            "document_types": ["SOW"],
            "severity": "critical",
            "check_type": "section_presence",
            "params": {"required_sections": ["Scope of Work", "Scope", "Work Scope", "Scope of Services"]},
            "recommendation": "Add a dedicated Scope of Work section defining all deliverables",
        },
        {
            "rule_id": "SOW-003",
            "name": "Deliverables Section Required",
            "description": "SOW must list all deliverables explicitly",
            "document_types": ["SOW"],
            "severity": "critical",
            "check_type": "section_presence",
            "params": {"required_sections": ["Deliverables", "Delivery Items", "Outputs"]},
            "recommendation": "Create a Deliverables section listing all outputs with acceptance criteria",
        },
        {
            "rule_id": "SOW-004",
            "name": "Timeline/Schedule Required",
            "description": "SOW must specify project timeline and milestones",
            "document_types": ["SOW"],
            "severity": "critical",
            "check_type": "section_presence",
            "params": {"required_sections": ["Timeline", "Schedule", "Milestones", "Project Timeline"]},
            "recommendation": "Add a Timeline section with start date, end date, and key milestones",
        },
        {
            "rule_id": "SOW-005",
            "name": "Pricing/Cost Section Required",
            "description": "SOW must specify pricing and cost structure",
            "document_types": ["SOW"],
            "severity": "critical",
            "check_type": "section_presence",
            "params": {"required_sections": ["Pricing", "Cost", "Fees", "Investment"]},
            "recommendation": "Add a Pricing section specifying total cost, payment terms, and invoice schedule",
        },
        {
            "rule_id": "SOW-006",
            "name": "Terms and Conditions Required",
            "description": "SOW must include Terms and Conditions section",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "section_presence",
            "params": {"required_sections": ["Terms and Conditions", "Terms", "T&C"]},
            "recommendation": "Add a Terms and Conditions section covering payment, liability, and termination",
        },
        {
            "rule_id": "SOW-007",
            "name": "Assumptions and Constraints Required",
            "description": "SOW must document assumptions and constraints",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "section_presence",
            "params": {"required_sections": ["Assumptions", "Constraints", "Assumptions & Constraints", "Assumptions and Dependencies"]},
            "recommendation": "Add Assumptions and Constraints section to clarify project boundaries",
        },
        # Word count rules (T-506)
        {
            "rule_id": "SOW-008",
            "name": "Scope Description Must Be Detailed",
            "description": "Scope of Work section must have sufficient detail (minimum 100 words)",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "word_count",
            "params": {"required_sections": ["Scope of Work", "Scope"], "min_words": 100},
            "recommendation": "Expand Scope section with more detailed description of work to be performed",
        },
        {
            "rule_id": "SOW-009",
            "name": "Deliverables Must Be Detailed",
            "description": "Deliverables section must have detailed descriptions (minimum 150 words)",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "word_count",
            "params": {"required_sections": ["Deliverables"], "min_words": 150},
            "recommendation": "Add detailed descriptions and acceptance criteria for each deliverable",
        },
        {
            "rule_id": "SOW-010",
            "name": "Terms Section Must Be Comprehensive",
            "description": "Terms and Conditions section must be comprehensive (minimum 100 words)",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "word_count",
            "params": {"required_sections": ["Terms and Conditions", "Terms"], "min_words": 100},
            "recommendation": "Expand Terms and Conditions with clear payment terms, liabilities, and dispute resolution",
        },
        # Keyword checks (T-508)
        {
            "rule_id": "SOW-011",
            "name": "Must Specify Payment Terms",
            "description": "SOW must explicitly mention payment terms (Net 30, Net 60, Due Upon Completion, etc.)",
            "document_types": ["SOW"],
            "severity": "critical",
            "check_type": "keyword",
            "params": {"keywords": ["net 30", "net 60", "net 90", "payment terms", "due upon", "invoice"]},
            "recommendation": "Add explicit payment terms in Pricing or Terms section (e.g., 'Net 30')",
        },
        {
            "rule_id": "SOW-012",
            "name": "Must Define Acceptance Criteria",
            "description": "SOW must define acceptance criteria for deliverables",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "keyword",
            "params": {"keywords": ["acceptance criteria", "acceptance", "acceptance date", "approved by", "signed off"]},
            "recommendation": "Define clear acceptance criteria for each deliverable (e.g., 'Approved by client, signed off by PM')",
        },
        {
            "rule_id": "SOW-013",
            "name": "Must Address Confidentiality",
            "description": "SOW should address confidentiality and data protection",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["confidential", "confidentiality", "nda", "data protection", "privacy"]},
            "recommendation": "Add confidentiality and data protection clauses in Terms section",
        },
        {
            "rule_id": "SOW-014",
            "name": "Must Address Change Control",
            "description": "SOW should define change control or change request process",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["change", "change request", "change control", "out of scope", "scope creep"]},
            "recommendation": "Add a Change Control section explaining how scope changes are handled",
        },
        # Conditional rules (T-507)
        {
            "rule_id": "SOW-015",
            "name": "High-Value SOW Must Have Escalation Clause",
            "description": "SOWs over $100K should have escalation/dispute resolution clause",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "conditional",
            "params": {
                "condition": "$100",
                "required_field": "escalation"
            },
            "recommendation": "For SOWs > $100K, add escalation/dispute resolution procedures in Terms",
        },
        {
            "rule_id": "SOW-016",
            "name": "Long-Term SOW Must Define Support",
            "description": "Multi-year SOWs (>12 months) should define post-delivery support",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "conditional",
            "params": {
                "condition": "year",
                "required_field": "support"
            },
            "recommendation": "For multi-year engagements, add post-delivery support and maintenance clauses",
        },
        # Regex rules (T-508)
        {
            "rule_id": "SOW-017",
            "name": "Must Have Start Date",
            "description": "SOW must specify a project start date (YYYY-MM-DD or similar format)",
            "document_types": ["SOW"],
            "severity": "critical",
            "check_type": "regex",
            "params": {
                "pattern": r"\d{4}-\d{2}-\d{2}|\d{1,2}/\d{1,2}/\d{4}|January|February|March|April|May|June|July|August|September|October|November|December.*\d{4}",
                "should_match": True
            },
            "recommendation": "Add an explicit start date in YYYY-MM-DD or other standard date format",
        },
        {
            "rule_id": "SOW-018",
            "name": "Must Have End Date or Duration",
            "description": "SOW must specify project end date or duration",
            "document_types": ["SOW"],
            "severity": "critical",
            "check_type": "regex",
            "params": {
                "pattern": r"end date|completion date|duration|weeks|months|days|through|until",
                "should_match": True
            },
            "recommendation": "Add project end date or specify duration (e.g., '6 months' or 'through 2026-12-31')",
        },
        {
            "rule_id": "SOW-019",
            "name": "Must Define Resource Requirements",
            "description": "SOW should specify team resources or staffing (FTE, roles, etc.)",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["resource", "fte", "team", "staffing", "personnel", "headcount"]},
            "recommendation": "Define resource requirements, team roles, and FTE allocation",
        },
        {
            "rule_id": "SOW-020",
            "name": "Must Address Success Metrics",
            "description": "SOW should define how project success will be measured",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["success criteria", "kpi", "metric", "measurement", "success"]},
            "recommendation": "Add Success Criteria section defining KPIs and how project success will be measured",
        },
        # SOW-021..SOW-033: 13 SOW-critical coverage checks from the SOW
        # Review Training Guideline §5 (docs/sample/SOW_Sample/
        # SOW_Review_Training_Guideline.md, added 2026-07-23). Keyword
        # checks over the full text rather than section_presence: these
        # concepts legitimately live inside other sections (RACI inside
        # "Roles and Responsibilities", DR inside a security section) or in
        # a referenced MSA -- heading-only matching would false-alarm.
        # Recommendations say "or reference the MSA section" for the same
        # reason.
        {
            "rule_id": "SOW-021",
            "name": "Must Define Project Milestones",
            "description": "SOW should define concrete project milestones or phase completion dates",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["milestone", "key dates", "phase completion"]},
            "recommendation": "Add dated milestones for each project phase, or reference the project plan that defines them",
        },
        {
            "rule_id": "SOW-022",
            "name": "Must Define KPIs",
            "description": "SOW should define key performance indicators for the service",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["kpi", "key performance indicator", "performance indicator", "performance metric"]},
            "recommendation": "Add a KPI section with measurable performance indicators, or reference the MSA/SLA schedule that defines them",
        },
        {
            "rule_id": "SOW-023",
            "name": "Must Define Service Credits or Penalties",
            "description": "SOW with SLAs should define service credits or penalties for missed service levels",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["service credit", "sla credit", "penalty", "penalties", "credit for missed"]},
            "recommendation": "Define service credits/penalties for SLA breaches, or reference the MSA section that covers remedies",
        },
        {
            "rule_id": "SOW-024",
            "name": "Must Include RACI or Responsibility Matrix",
            "description": "SOW should include a RACI or responsibility assignment matrix clarifying ownership",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "keyword",
            "params": {"keywords": ["raci", "responsibility matrix", "responsibility assignment"]},
            "recommendation": "Add a RACI matrix mapping each activity to Responsible/Accountable/Consulted/Informed parties",
        },
        {
            "rule_id": "SOW-025",
            "name": "Must Address Compliance Requirements",
            "description": "SOW should state applicable regulatory/compliance requirements (ISO, SOC 2, GDPR, etc.)",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "keyword",
            "params": {"keywords": ["compliance", "regulatory", "iso 27001", "soc 2", "gdpr", "hipaa"]},
            "recommendation": "State the compliance standards the service must meet, or reference the MSA compliance schedule",
        },
        {
            "rule_id": "SOW-026",
            "name": "Must Address Data Retention",
            "description": "SOW should define data retention periods and disposal policy",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["data retention", "retention period", "retention policy", "data disposal"]},
            "recommendation": "Define how long service data (logs, tickets, reports) is retained and how it is disposed, or reference the MSA data-handling section",
        },
        {
            "rule_id": "SOW-027",
            "name": "Must Define Exit/Transition-Out Plan",
            "description": "SOW should define an exit or transition-out plan for contract end",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "keyword",
            "params": {"keywords": ["transition-out", "transition out", "exit plan", "termination assistance", "offboarding", "disengagement"]},
            "recommendation": "Add an exit/transition-out plan covering knowledge transfer, data return, and handover duties, or reference the MSA termination section",
        },
        {
            "rule_id": "SOW-028",
            "name": "Must Address Disaster Recovery",
            "description": "SOW should address disaster recovery for the delivered service",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["disaster recovery", "dr plan", "rto", "rpo"]},
            "recommendation": "State DR commitments (RTO/RPO) for the service, or reference the MSA/DR schedule that covers it",
        },
        {
            "rule_id": "SOW-029",
            "name": "Must Address Business Continuity",
            "description": "SOW should address business continuity for the delivered service",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["business continuity", "bcp", "continuity plan"]},
            "recommendation": "State business continuity arrangements for the service, or reference the MSA/BCP document that covers it",
        },
        {
            "rule_id": "SOW-030",
            "name": "Must Address Intellectual Property Ownership",
            "description": "SOW should state who owns work product and deliverables",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "keyword",
            "params": {"keywords": ["intellectual property", "ip ownership", "work product", "ownership of deliverables", "work for hire"]},
            "recommendation": "State IP/work-product ownership explicitly, or reference the MSA IP section",
        },
        {
            "rule_id": "SOW-031",
            "name": "Must Define Payment Schedule",
            "description": "SOW should define when and how payments occur (schedule/cadence, not just terms)",
            "document_types": ["SOW"],
            "severity": "major",
            "check_type": "keyword",
            "params": {"keywords": ["payment schedule", "invoicing schedule", "billing schedule", "payment milestone", "monthly in arrears", "invoiced monthly"]},
            "recommendation": "Add a payment schedule (amounts, cadence, invoicing trigger), or reference the MSA billing section",
        },
        {
            "rule_id": "SOW-032",
            "name": "Must State Customer Staffing Assumptions",
            "description": "SOW should state what staffing/resources the customer must provide",
            "document_types": ["SOW"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["customer staffing", "client staffing", "customer resources", "client resources", "customer shall provide", "client shall provide", "customer-provided", "client-provided"]},
            "recommendation": "State the staffing/resources the customer must provide (roles, availability, SLAs on their obligations)",
        },
        {
            "rule_id": "SOW-033",
            "name": "Should Include Glossary",
            "description": "SOW should include a glossary or definitions for key/technical terms",
            "document_types": ["SOW"],
            "severity": "low",
            "check_type": "keyword",
            "params": {"keywords": ["glossary", "definitions", "defined terms", "acronyms"]},
            "recommendation": "Add a glossary defining technical terms and acronyms used in the SOW",
        },
        # RFP rules (T-2xxx: RFP document type support)
        # Evaluation criteria
        {
            "rule_id": "RFP-001",
            "name": "Evaluation Criteria Section Required",
            "description": "RFP must contain a section describing how proposals will be evaluated",
            "document_types": ["RFP"],
            "severity": "critical",
            "check_type": "section_presence",
            "params": {"required_sections": ["Evaluation Criteria", "Proposal Evaluation", "Scoring Criteria"]},
            "recommendation": "Add an Evaluation Criteria section explaining how submitted proposals will be scored",
        },
        {
            "rule_id": "RFP-002",
            "name": "Evaluation Criteria Must Be Detailed",
            "description": "Evaluation Criteria section must have sufficient detail (minimum 75 words)",
            "document_types": ["RFP"],
            "severity": "major",
            "check_type": "word_count",
            "params": {"required_sections": ["Evaluation Criteria"], "min_words": 75},
            "recommendation": "Expand Evaluation Criteria with scoring weights and rating methodology per category",
        },
        {
            "rule_id": "RFP-003",
            "name": "Must Reference Scoring Weights",
            "description": "RFP should specify relative weighting of evaluation categories",
            "document_types": ["RFP"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["weight", "weighted", "points", "score"]},
            "recommendation": "Disclose the weighting or point allocation for each evaluation category",
        },
        # Vendor qualification requirements
        {
            "rule_id": "RFP-004",
            "name": "Vendor Qualifications Section Required",
            "description": "RFP must define minimum vendor qualification requirements",
            "document_types": ["RFP"],
            "severity": "critical",
            "check_type": "section_presence",
            "params": {"required_sections": ["Vendor Qualifications", "Qualifications", "Bidder Requirements"]},
            "recommendation": "Add a Vendor Qualifications section listing required experience, certifications, and references",
        },
        {
            "rule_id": "RFP-005",
            "name": "Must Require References or Past Performance",
            "description": "RFP should require vendors to submit references or past performance examples",
            "document_types": ["RFP"],
            "severity": "major",
            "check_type": "keyword",
            "params": {"keywords": ["references", "past performance", "case studies", "client references"]},
            "recommendation": "Require vendors to submit at least 2-3 client references or past performance summaries",
        },
        {
            "rule_id": "RFP-006",
            "name": "Must Address Certifications or Licensing",
            "description": "RFP should specify required certifications, licenses, or minimum experience",
            "document_types": ["RFP"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["certification", "certified", "license", "years of experience", "minimum experience"]},
            "recommendation": "Specify required certifications, licenses, or minimum years of relevant experience",
        },
        # Submission format and deadline
        {
            "rule_id": "RFP-007",
            "name": "Submission Requirements Section Required",
            "description": "RFP must define how and in what format proposals must be submitted",
            "document_types": ["RFP"],
            "severity": "critical",
            "check_type": "section_presence",
            "params": {"required_sections": ["Submission Requirements", "Submission Instructions", "How to Submit"]},
            "recommendation": "Add a Submission Requirements section covering format, delivery method, and page limits",
        },
        {
            "rule_id": "RFP-008",
            "name": "Must Have Submission Deadline",
            "description": "RFP must specify an explicit proposal submission deadline (date format)",
            "document_types": ["RFP"],
            "severity": "critical",
            "check_type": "regex",
            "params": {
                "pattern": r"\d{4}-\d{2}-\d{2}|\d{1,2}/\d{1,2}/\d{4}|January|February|March|April|May|June|July|August|September|October|November|December.*\d{4}",
                "should_match": True
            },
            "recommendation": "Add an explicit submission deadline in YYYY-MM-DD or other standard date format",
        },
        {
            "rule_id": "RFP-009",
            "name": "Must Specify Submission Format",
            "description": "RFP should specify required file format for proposal submission (e.g., PDF)",
            "document_types": ["RFP"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["pdf", "format", "electronic submission", "hard copy"]},
            "recommendation": "Specify the required submission file format (e.g., 'PDF, submitted via email')",
        },
        {
            "rule_id": "RFP-010",
            "name": "Should Specify Page Limit",
            "description": "RFP should specify a maximum page count for proposals",
            "document_types": ["RFP"],
            "severity": "low",
            "check_type": "keyword",
            "params": {"keywords": ["page limit", "maximum pages", "not to exceed", "page count"]},
            "recommendation": "Add a page limit to keep proposals concise and comparable across vendors",
        },
        # Q&A / clarification process
        {
            "rule_id": "RFP-011",
            "name": "Q&A Process Section Required",
            "description": "RFP must describe the vendor question and clarification process",
            "document_types": ["RFP"],
            "severity": "major",
            "check_type": "section_presence",
            "params": {"required_sections": ["Q&A Process", "Questions and Answers", "Clarification Process"]},
            "recommendation": "Add a Q&A Process section describing how vendors may submit questions and receive answers",
        },
        {
            "rule_id": "RFP-012",
            "name": "Must Define Question Submission Window",
            "description": "RFP should define a deadline for vendors to submit clarification questions",
            "document_types": ["RFP"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["question deadline", "questions due", "inquiry period", "clarification deadline"]},
            "recommendation": "Specify a deadline by which vendors must submit clarification questions",
        },
        {
            "rule_id": "RFP-013",
            "name": "Must Address How Answers Are Published",
            "description": "RFP should describe how answers to vendor questions will be distributed",
            "document_types": ["RFP"],
            "severity": "low",
            "check_type": "keyword",
            "params": {"keywords": ["published", "posted", "addendum", "distributed to all"]},
            "recommendation": "Explain how Q&A answers will be published to all bidders (e.g., addendum posted to all vendors)",
        },
        # Award criteria / decision process
        {
            "rule_id": "RFP-014",
            "name": "Award Notification Section Required",
            "description": "RFP must describe how and when the award decision will be communicated",
            "document_types": ["RFP"],
            "severity": "major",
            "check_type": "section_presence",
            "params": {"required_sections": ["Award Notification", "Award Process", "Contract Award"]},
            "recommendation": "Add an Award Notification section describing the selection process and notification timeline",
        },
        {
            "rule_id": "RFP-015",
            "name": "Must Specify Award Decision Timeline",
            "description": "RFP should specify an expected timeline for the award decision",
            "document_types": ["RFP"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["award date", "decision date", "notification date", "selection timeline"]},
            "recommendation": "Add an expected date or timeframe for when the award decision will be announced",
        },
        {
            "rule_id": "RFP-016",
            "name": "Must Reserve Right to Reject Proposals",
            "description": "RFP should reserve the issuer's right to reject any or all proposals",
            "document_types": ["RFP"],
            "severity": "low",
            "check_type": "keyword",
            "params": {"keywords": ["right to reject", "reserves the right", "no obligation to award"]},
            "recommendation": "Add standard language reserving the right to reject any or all proposals",
        },
        # General RFP hygiene
        {
            "rule_id": "RFP-017",
            "name": "Scope of Request Section Required",
            "description": "RFP must clearly describe the scope of work being solicited from vendors",
            "document_types": ["RFP"],
            "severity": "critical",
            "check_type": "section_presence",
            "params": {"required_sections": ["Scope of Request", "Scope of Work Requested", "Project Overview"]},
            "recommendation": "Add a Scope of Request section describing what work/services are being solicited",
        },
        {
            "rule_id": "RFP-018",
            "name": "Should Disclose Budget Range",
            "description": "RFP should disclose an estimated budget range to help vendors scope their proposals",
            "document_types": ["RFP"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["budget range", "estimated budget", "budget of", "not to exceed budget"]},
            "recommendation": "Consider disclosing an estimated budget range to improve proposal fit and comparability",
        },
        {
            "rule_id": "RFP-019",
            "name": "Must Address Confidentiality/NDA for Bidders",
            "description": "RFP should require confidentiality or NDA acknowledgment from bidders",
            "document_types": ["RFP"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["confidential", "confidentiality", "nda", "non-disclosure"]},
            "recommendation": "Add a confidentiality/NDA requirement for vendors accessing RFP materials",
        },
        {
            "rule_id": "RFP-020",
            "name": "Should Preview Contract Terms",
            "description": "RFP should disclose the contract terms that the winning vendor will be bound to",
            "document_types": ["RFP"],
            "severity": "medium",
            "check_type": "keyword",
            "params": {"keywords": ["contract terms", "sample contract", "master service agreement", "terms and conditions"]},
            "recommendation": "Attach or summarize the contract terms the awarded vendor will be required to accept",
        },
    ]
