"""Generate upload-ready MITRE sample files from a real customer workbook shape.

Source: the screenshots in docs/sample/MITRE_Sample/UploadSample/ — a live
Microsoft Sentinel "Consolidated Usecase Tracker" plus a device/technology
inventory. This reproduces that EXACT column and sheet layout (anonymized:
the customer prefix becomes "ACME") so the upload path can be demoed and
tested against a realistic file rather than our own template.

Run from apps/api (needs the app's Python env):

    python ../../scripts/generate_uploadsample.py

Every technique ID is validated against the pinned ATT&CK dataset and the
files are round-tripped through the real ingest parsers; the script hard-fails
if anything drifts.
"""

import sys
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill

from app.mitre import attack_data, ingest

OUT = Path(__file__).resolve().parents[1] / "docs/sample/MITRE_Sample/UploadSample"

# --------------------------------------------------------------------------
# 1. Use-case tracker — the customer's own column layout, verbatim
#    (S.No | Analytical Rule | Description | Datasource Used | Use Case Type |
#     RuleType | Severity | Query / Conditions | MITRE Tactics |
#     MITRE Techniques | Validation Result | Status | Implementation Date)
# --------------------------------------------------------------------------
UC_HEADERS = [
    "S.No", "Analytical Rule", "Description", "Datasource Used",
    "Use Case Type", "RuleType", "Severity", "Query / Conditions",
    "MITRE Tactics", "MITRE Techniques", "Validation Result", "Status",
    "Implementation Date",
]

# (name, description, datasource, type, ruletype, severity, query, tactics,
#  techniques, validation, status, date)
RULES = [
    ("ACME_Custom_FW policy monitoring",
     "Triggered whenever updates, including edits or deletions, occur in the Firewall policy within INT-VDOM and in Policy ID 68.",
     "Fortinet", "Scheduled", "Custom", "Informational",
     'CommonSecurityLog | where DeviceEventCategory == "event:system" | where Message has "firewall.policy"',
     "Defense Evasion", "T1562 - Impair DefensesT1562.004 - Disable or Modify System Firewall",
     "Validate data from past two months and no result found.", "Enabled", "1/25/2026"),
    ("ACME_Custom_arbor_alert_for_ddos (Impact greater than 10 GB)",
     "Alerts when Arbor (NetScout) identifies traffic patterns consistent with a Network Denial of Service (DoS/DDoS) attack.",
     "NetScout", "Scheduled", "Customer Specific", "Informational",
     'NetScout_lpnet_CL | extend AlertID = extract("@spAlertID (\\d+)", 1, rawevent)',
     "Impact", "T1498 - Network Denial of ServiceT1499 - Endpoint Denial of Service",
     "Validate data from past two months, and 7 result found.", "Enabled", ""),
    ("Rare and potentially high-risk Office operations",
     "Office operations that are typically rare and can provide capabilities useful to attackers.",
     "Microsoft 365 (formerly, Office 365)OfficeActivity (Exchange)", "Scheduled", "OOB", "Informational",
     'OfficeActivity | where Operation in~ ("Add-MailboxPermission", "Set-Mailbox", "New-ManagementRoleAssignment")',
     "Persistence,Collection", "T1114 - Email Collection",
     "Verified data from the past two months, and 7 result found.", "Enabled", "24-Nov-25"),
    ("Failed login attempts to Azure Portal",
     "Failed login attempts in the Microsoft Entra ID SigninLogs to the Azure Portal. Many failed logon attempts from multiple IPs could indicate a password-spray attempt.",
     "Microsoft Entra IDSigninLogs", "Scheduled", "OOB", "Informational",
     'let timeRange = 1d; let lookBack = 7d; let threshold_Failed = 5; let threshold_FailedwithSingleIP = 20;',
     "Credential Access", "T1110 - Brute Force",
     "Verified data from the past two months, and 3 result found.", "Enabled", "24-Nov-25"),
    ("ACME_Custom_Palo Alto Cortex XDR Incident",
     "Triggered when low severity security incidents from Palo Alto Cortex XDR that are not automatically resolved and involve at least one host or user.",
     "PaloAltoCortexXDR", "Scheduled", "Custom", "Informational",
     '//let delay = 2h;//let freq = 1h; PaloAltoCortexXDR_Incidents_CL | where TimeGenerated >= ago(delay + freq)',
     "NA", "NA",
     "Verified data from past 24 hours and 21 result found.", "Enabled", "3/2/2026"),
    ("ACME_Custom_users sharing C3/C4 classified documents to external domain",
     "Triggered when employees attempt to share C3/C4 (highly sensitive) documents from Microsoft 365 services such as SharePoint, OneDrive or Teams with external domains.",
     "MicrosoftPurviewInformation Protection", "Scheduled", "Custom", "Informational",
     'MicrosoftPurviewInformationProtection | where LabelName has_any ("C3","C4") | where Sender != ""',
     "Exfiltration", "T1567 - Exfiltration Over Web Service",
     "Verified data from past 24 hours and 218 result found.", "Enabled", "1/29/2026"),
    ("ACME_Custom_VIP users sharing documents to external domain",
     "Triggered when a DLP policy detects a VIP user sharing documents with an external domain.",
     "MicrosoftPurviewInformation Protection", "Scheduled", "Custom", "Informational",
     'let VIPUser = ( _GetWatchlist("vipuser") | project SearchKey); EmailAttachmentInfo | where SenderFromAddress in~ (VIPUser)',
     "Exfiltration", "T1567 - Exfiltration Over Web Service",
     "Verified data from past 24 hours and 21 result found.", "Enabled", "1/26/2026"),
    ("ACME_Custom_Auto resolve incident in MDE",
     "Identifies Microsoft Defender for Endpoint incidents automatically resolved by the Automated Investigation and Response (AIR) engine.",
     "SecurityAlert", "Scheduled", "Custom", "Informational",
     '// 1) Identify the MDATP alerts resolved by AIR: let target_alerts = SecurityAlert | where ProviderName == "MDATP"',
     "N/A", "N/A",
     "Verified data from past 1 hours and no result found.", "Enabled", "2/26/2026"),
    ("ACME_Custom_Group Member Added in security-enabled group",
     "A member is added to a security-enabled global, local, or universal group on Windows Server. Helps monitor unauthorized group membership changes.",
     "Windows Security Events via AMA", "Scheduled", "Custom", "Low",
     'let WellKnownLocalSID = "S-1-5-32-5[0-9][0-9]$"; SecurityEvent | where EventID in (4728, 4732, 4756)',
     "Persistence, Privilege Escalation", "T1098 - Account ManipulationT1098.001 - Additional Cloud Credentials",
     "Verified data from past two months and no results found.", "Enabled", "5/1/2026"),
    ("ACME_Custom_Windows - Kerberoasting Detection via multiple service request",
     "Detects potential Kerberoasting activity by identifying instances where a single user requests an unusually high number of Kerberos service tickets within a 10-minute window.",
     "SecurityEvent", "Scheduled", "Custom COE", "Low",
     'let TestLookback = 14d; let DetectionWindow = 1h; let BinSize = 20m; SecurityEvent | where EventID == 4769',
     "Credential Access", "T1558 - Steal or Forge Kerberos Tickets",
     "Validate data from past 1 Hours and no result found.", "Enabled", "4/3/2026"),
    ("SSH - Potential Brute Force",
     "Identifies an IP address that had 15 failed attempts to sign in via SSH in a rolling 24 hour time period.",
     "Syslog via AMA", "Scheduled", "OOB", "Low",
     'let threshold = 15; Syslog | where SyslogMessage contains "Failed password for invalid user" | parse SyslogMessage',
     "Credential Access", "T1110 - Brute Force",
     "Verified data from past two months and no results found.", "Enabled", "2/2/2026"),
    ("ACME_Custom_VPN User Deleted",
     "Detects alerts from Fortiauthenticator for VPN user deletion, when the user is Midhat in business hours.",
     "Fortinet VPN", "Scheduled", "Customer Specific", "Low",
     'let TzOffset = 3h; // UTC+03:00 (Qatar) — no DST; let BusinessStartHour = 8; let BusinessEndHour = 17;',
     "Privilege Escalation,Impact", "T1098 - Account ManipulationT1531 - Account Access Removal",
     "Verified data from past two months, and 17 result found.", "Enabled", "1/20/2026"),
    ("ACME_Custom_usage of forbidden applications",
     "Triggered when a user is accessing unsanctioned or forbidden applications.",
     "Windows Security Events via AMA", "Scheduled", "Custom COE", "Low",
     'let forbidden_applications = dynamic(["AnyDesk","TeamViewer","Telegram","Discord","RustDesk","LogMeIn","VNC","GoogleDrive"]);',
     "Exfiltration, Command And Control", "T1567 - Exfiltration Over Web ServiceT1105 - Ingress Tool Transfer",
     "Verified data from past two months and 16 result found.", "Enabled", "1/20/2026"),
    ("Excessive Windows Logon Failures",
     "Identifies user accounts which have over 50 Windows logon failures today and at least 33% of the count of logon failures over the previous 7 days.",
     "Windows Security Events via AMA", "Scheduled", "OOB", "Low",
     'let starttime = 8d; let endtime = 1d; let threshold = 0.333; let countlimit = 50; SecurityEvent | where TimeGenerated >= ago(endtime)',
     "Credential Access", "T1110 - Brute Force",
     "Verified data from past two months and no results found.", "Enabled", "26-Jan-26"),
    ("TI map IP Entity to CommonSecurityLog",
     "Maps IP indicators of compromise (IOCs) from threat intelligence (TI) by searching for matches in CommonSecurityLog.",
     "Common Event Format (CEF)", "Scheduled", "Custom COE", "Low",
     'let IPRegex = "[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"; let dt_lookBack = 1h; // Look back 1 hour',
     "Command And Control", "T1071 - Application Layer Protocol",
     "Verified data from past 24 Hours and no results found.", "Enabled", "26-Jan-26"),
    ("ACME_Custom_Cyberark-Suspicious Password Usage at PIM from Privileged Accounts",
     "Detects attempts of CyberArk operations from privileged accounts.",
     "CyberArc_CL", "Scheduled", "Custom Specific", "Low",
     'CyberArk_CL | where act has_any ("Retrieve password","PSM Connect","Use Password") | where userName has_any ("Administrator","svc-")',
     "Credential Access", "T1555 - Credentials from Password Stores",
     "Verified data from past 24 Hours and no result found.", "Enabled", "3/2/2026"),
    ("ACME_Custom_Windows-Entra ID User Added To Local Administrators Group Detected",
     "Detects when a new local account is created and added to the local Administrators group.",
     "SecurityEvent", "Scheduled", "Custom COE", "Low",
     'SecurityEvent | where (EventID == 4732 and (TargetUserName contains "adm")) and ((SubjectUserName != TargetUserName))',
     "Persistence", "T1098 - Account ManipulationT1098.003 - Additional Cloud Roles",
     "Verified data from past 1 Hours and no result found.", "Enabled", ""),
    ("ACME_Custom_Windows-Possible DCSync Attack via Audit",
     "DCSync is a late stage kill chain attack that allows an attacker to simulate the behavior of a Domain Controller (DC) to retrieve password data via domain replication.",
     "SecurityEvent", "Scheduled", "Custom COE", "Low",
     'SecurityEvent | where EventID == 4662 | where AccessMask == "0x100" | where ObjectServer == "DS"',
     "Credential Access, Discovery", "T1003 - OS Credential Dumping",
     "Verified data from past 1 Hours and no result found.", "Enabled", "4/3/2026"),
    ("ACME_Custom__Paloalto_Cortex_XDR_Medium_Alert_Block",
     "Identifies notifiable blocked alerts triggered by PA Cortex XDR (Cortex XDR Medium Blocked Alerts with Medium Severity).",
     "Paloalto Cortex XDR", "Scheduled", "Custom", "Low",
     'PaloAltoCortexXDR_Alerts_CL | where Severity == "medium" | where Action contains "blocked"',
     "Not Available", "Not Available",
     "Validate data from past two months and 36 result found.", "Enabled", "8/1/2026"),
    ("Mass Cloud resource deletions Time Series Anomaly",
     "Identifies the baseline pattern of cloud resource deletions by an individual and generates an anomaly when any unusual spike is detected.",
     "Azure Activity", "Scheduled", "OOB", "Low",
     'let starttime = 14d; let endtime = 1d; let timeframe = 1d; let TotalEventsThreshold = 25;',
     "Impact", "T1485 - Data Destruction",
     "Verified data from past two months, and no results found.", "Enabled", "24-Nov-25"),
    ("ACME_Custom_Windows - Kerberoasting Detection ASIM Network Session",
     "Detects a match in Network Session Events data from any IP indicator from TI.",
     "Security Events via Legacy AgentWindows Forwarded EventsAzure Firewall", "Scheduled", "OOB", "Low",
     'let dt_lookBack = 1h; let ioc_lookBack = 14d; let DeviceNetworkEvents = _DeviceNetworkEvents | where isnotempty(RemoteIP)',
     "Command And Control", "T1071 - Application Layer Protocol",
     "Verified data from past two months and no results found.", "Enabled", "29-Nov-25"),
    ("SharePointFileOperation via devices with previously unseen user agents",
     "Identifies anomalies in the number of documents uploaded or downloaded from devices associated with a previously unseen user agent.",
     "Microsoft 365 (formerly, Office 365)", "Scheduled", "OOB", "Low",
     '// Set threshold for the number of downloads/uploads from a new user agent; let threshold = 5;',
     "Exfiltration", "T1030 - Data Transfer Size Limits",
     "Verified data from past two months, and 1 result found.", "Enabled", ""),
    ("Azure Portal sign in from another Azure tenant",
     "Looks for successful sign in attempts to the Azure Portal where the user who is signing in from another Azure tenant.",
     "Microsoft Entra IDSigninLogs", "Scheduled", "OOB", "Low",
     '// Get details of current Azure Ranges (note this URL updates regularly so will need to be manually updated)',
     "Initial Access", "T1199 - Trusted Relationship",
     "Verified data from past two months and no results found.", "Enabled", "26-Jan-26"),
    ("Log4j vulnerability exploit aka Log4Shell IP IOC",
     "Identifies a match across various data feeds for IP IOCs related to the Log4j vulnerability exploit aka Log4Shell described in CVE-2021-44228.",
     "Microsoft Entra IDSigninLogs", "Scheduled", "OOB", "High",
     'let IPList = externaldata(IPAddress:string)[@"https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Sample%20Data/Feeds/Log4j_IOC_List.csv"]',
     "Command And Control", "T1071 - Application Layer Protocol",
     "Verified data from past two months, and 218 result found.", "Enabled", "3/2/2026"),
    ("Attempt to bypass conditional access rule(s) in Microsoft Entra ID",
     "Identifies an attempt to bypass conditional access rule(s) in Microsoft Entra ID.",
     "Microsoft Entra IDSigninLogs", "Scheduled", "OOB", "High",
     'let threshold = 1; // Modify this threshold value to reduce false positives based on your environment',
     "Initial Access,Persistence", "T1078 - Valid AccountsT1078 - Valid AccountsT1098 - Account Manipulation",
     "Verified data from past two months, and 83 results found.", "Enabled", "26-Jan-26"),
    ("Squid proxy events for TOR proxies",
     "Check for Squid proxy events associated with common ToR proxies. This query presumes the default Squid log format is being used.",
     "Syslog via AMA", "Scheduled", "OOB", "High",
     'let DomainList = dynamic(["tor2web.org","tor2web.com","torlink.co","onion.to","onion.in","onion.ink"]);',
     "Command And Control", "T1008 - Fallback ChannelsT1090 - Proxy",
     "Verified data from past two months and no results found.", "Enabled", "2-Feb-26"),
    ("NRT Sensitive Azure Key Vault operations",
     "Identifies when sensitive Azure Key Vault operations are used. This includes: VaultDelete, KeyDelete, SecretDelete, SecretPurge, KeyPurge, SecretBackup, KeyBackup, KeyList.",
     "Azure Key Vault", "NRT", "OOB", "High",
     'let SensitiveOperationList = dynamic(["VaultDelete","KeyDelete","SecretDelete","SecretPurge","KeyPurge","SecretBackup"]);',
     "Impact", "T1485 - Data Destruction",
     "Verified data from past two months and no results found.", "Enabled", "25-Jan-26"),
    ("Sensitive Azure Key Vault operations",
     "Identifies when sensitive Azure Key Vault operations are used, in the scheduled (non-NRT) variant.",
     "Azure Key Vault", "Scheduled", "OOB", "High",
     'let SensitiveOperationList = dynamic(["VaultDelete","KeyDelete","SecretDelete","SecretPurge","KeyPurge","SecretBackup"]);',
     "Impact", "T1485 - Data Destruction",
     "Verified data from past two months and no results found.", "Disabled", "25-Jan-26"),
    ("SecurityEvent - Multiple authentication failures followed by a success",
     "Identifies accounts who have failed to logon to the domain multiple times in a row, followed by a successful authentication within a short time frame.",
     "Windows Security Events via AMA", "Scheduled", "OOB", "High",
     'let timeRange = 2h; let authenticationWindow = 1h; let authenticationThreshold = 5; SecurityEvent | where EventID == 4625',
     "Credential Access", "T1110 - Brute Force",
     "Verified data from past two months, and 5 result found.", "Enabled", "25-Jan-26"),
    ("Potential re-named sdelete usage",
     "Detects command line parameters associated with the use of Sysinternals sdelete.",
     "SecurityEvent", "Scheduled", "OOB", "High",
     'SecurityEvent | where EventID == 4688 | where Process != "sdelete.exe" | where CommandLine has_all ("-accepteula", "-r", "-s", "-q")',
     "Defense Evasion, Impact", "T1485 - Data DestructionT1070 - Indicator Removal",
     "Verified data from past two months and no results found.", "Enabled", "25-Jan-26"),
    ("Azure Machine Learning Write Operations",
     "Shows the most prevalent users who perform write operations on Azure Machine Learning resources.",
     "Azure Activity", "Scheduled", "OOB", "High",
     'AzureActivity | where ResourceProviderValue == "MICROSOFT.MACHINELEARNINGSERVICES" // Filter activities related to Microsoft ML',
     "Execution", "T1059 - Command and Scripting Interpreter",
     "Verified data from past two months and no results found.", "Enabled", "26-Jan-26"),
    ("New CloudShell User",
     "Identifies when a user creates an Azure CloudShell for the first time. Monitor this activity to ensure only the expected users are using CloudShell.",
     "Azure Firewall", "Scheduled", "OOB", "High",
     'let match_window = 3m; AzureActivity | where ResourceGroup has "cloud-shell" | where OperationNameValue == "MICROSOFT.STORAGE"',
     "Execution", "T1059 - Command and Scripting Interpreter",
     "Verified data from past two months and no results found.", "Enabled", "25-Jan-26"),
    ("Mass secret retrieval from Azure Key Vault",
     "Identifies mass secret retrieval from Azure Key Vault observed by a single user. Mass secret retrieval crossing a certain threshold is an indication of credential dump operations.",
     "Azure Key Vault", "Scheduled", "OOB", "High",
     'let DistinctSecretsThreshold = 10; let EventCountThreshold = 50; // To avoid any False Positives, filtering using AppId is recommended',
     "Credential Access", "T1003 - OS Credential Dumping",
     "Verified data from past two months, and three results found.", "Enabled", "25-Jan-26"),
    ("Azure Service Principal created on-prem",
     "Alerts when creation of an SPN, permissions granted, credentials created, and/or deletion of the SPN in a short time frame.",
     "Microsoft Entra IDAuditLogsAADServicePrincipalSignInLogs", "Scheduled", "Qatar Framework", "High",
     'let SelectedUsers = dynamic(["user1@contoso.com","user2@contoso.com"]); AuditLogs | where ActivityDisplayName == "Add service principal"',
     "Credential Access,Privilege EscalationInitial Access", "T1528 - Steal Application Access TokenT1078 - Valid Accounts",
     "This query is monitoring particular user when required.", "Enabled", "9-Dec-25"),
    ("NRT Privileged Role Assigned Outside PIM",
     "A privileged role being assigned to a user outside of PIM.",
     "Microsoft Entra IDAuditLogs", "NRT", "OOB", "High",
     'AuditLogs | where Category == "RoleManagement" | where OperationName has "Add member to role outside of PIM"',
     "Privilege Escalation", "T1078 - Valid AccountsT1078.004 - Cloud Accounts",
     "Verified data from past two months and no results found.", "Enabled", "24-Nov-25"),
    ("Subscription moved to another tenant",
     "Uses Azure Activity logs (Security category) to identify when a subscription is moved to another tenant. A threat actor may move a subscription into their own tenant.",
     "Azure Activity", "Scheduled", "OOB", "High",
     'let queryFrequency = 5m; let eventCapture = "moved from tenant"; AzureActivity | where OperationNameValue has eventCapture',
     "Impact", "T1496 - Resource Hijacking",
     "Verified data from past two months and no results found.", "Enabled", ""),
    ("External user added and removed in short timeframe",
     "Flags the occurrences of external user accounts that are added to a Team and then removed within one hour.",
     "Microsoft 365 (formerly, Office 365)OfficeActivity (Teams)", "Scheduled", "OOB", "High",
     'let TeamsAddDel = (OfficeActivity | where OfficeWorkload == "MicrosoftTeams" | where Operation == "MemberAdded")',
     "Persistence", "T1136 - Create Account",
     "Verified data from past two months, and 1 result found.", "Enabled", "24-Nov-25"),
    ("Accessed files shared by temporary external user",
     "Identifies when an external user is added to a Team or Teams chat and shares a file which is accessed by many users (>10) and the users are removed within 7 days.",
     "Microsoft 365 (formerly, Office 365)OfficeActivity (Teams)", "Scheduled", "OOB", "High",
     'let fileAccessThreshold = 10; OfficeActivity | where OfficeWorkload == "MicrosoftTeams" | where Operation == "MemberAdded"',
     "Initial Access", "T1566 - Phishing",
     "Verified data from past two months and no results found.", "Enabled", "9-Dec-25"),
    ("ACME_Custom_A sequence of a port scan then followed by exploitation such as SQL injection",
     "Identifies a multi-stage attack pattern where an attacker first performs a port scan to enumerate open services and then attempts an SQL injection exploit.",
     "Azure Firewall, Fortigate Firewall", "Scheduled", "Qatar Framework", "High",
     'let Lookback = 45m; // overall lookback; let ScanBinMinutes = 10m; // bin scans in 10-min chunks',
     "Reconnaissance,Initial Access,Execution", "T1595 - Active ScanningT1059 - Command and Scripting InterpreterT1190 - Exploit Public-Facing Application",
     "Verified data from past two months and no results found.", "Enabled", "5/20/2026"),
    ("ACME_Syslog -Possible CVE-2026-43284/43500 Dirty Frag Exploitation",
     "Detects possible exploitation of CVE-2026-43284/43500 (Dirty Frag) on Linux by correlating suspicious process or audit activity associated with abuse indicators.",
     "Syslog", "Scheduled", "Customer Specific", "High",
     'let Lookback = 15m; // Scenario 1: Generic exploit indicators',
     "Reconnaissance,Execution,PrivilegeEscalation", "T1595 - Active ScanningT1059 - Command and Scripting InterpreterT1068 - Exploitation for Privilege Escalation",
     "Verified data from past two months and no results found.", "Enabled", "5/20/2026"),
    ("ACME_Custom_XDR-Possible CVE-2026-43284/43500 Dirty Frag Exploitation",
     "Detects possible exploitation of CVE-2026-43284/43500 (Dirty Frag) via the XDR telemetry path.",
     "XDR", "Scheduled", "Customer Specific", "High",
     'let Lookback = 15m; // XDR variant of the Dirty Frag detection',
     "Reconnaissance,Execution,PrivilegeEscalation", "T1595 - Active ScanningT1068 - Exploitation for Privilege Escalation",
     "Verified data from past two months and no results found.", "Enabled", "5/20/2026"),
    ("ACME_Custom_DNOC Access Operations – Unauthorized SSH Login Success from SFTP",
     "Detects SSH login success attempts performed by users who are restricted to SFTP-only access but are attempting interactive SSH connections.",
     "Access Operations", "Scheduled", "Custom COE", "High",
     'let IPUserWatchlistKeys = (_GetWatchlist("DNOCServer") | project Hostname = tolower(trim(" ", tostring(Hostname))));',
     "Initial Access,Persistence", "T1078 - Valid Accounts",
     "Verified data from past two months and no results found.", "Enabled", "5/14/2026"),
    ("ACME_Custom_Security alert matching Iran SITREP IOC",
     "Connection or event observed involving IP included in Iran SITREP IOC watchlist.",
     "SecurityAlert", "Scheduled", "Custom COE", "High",
     'let Watchlist = (_GetWatchlist("IOC") | project IPAddress); SecurityAlert | extend EntitiesDynamicArray = parse_json(Entities)',
     "Initial Access,Command And Control", "T1071 - Application Layer Protocol",
     "Verified data from past two months, and no results found.", "Enabled", "2/3/2026"),
    ("ACME_Custom_Incoming or outgoing communication with TOR hosts",
     "Identifies devices that establish inbound or outbound network connections to IP addresses associated with TOR nodes or other high-risk infrastructure (Botnet, Malware, C2).",
     "DeviceNetworkEvents, ThreatIntelligenceIndicator", "Scheduled", "Custom COE", "High",
     'let TimeWindow = 7d; DeviceNetworkEvents | where TimeGenerated > ago(TimeWindow) | where RemoteIPType == "Public"',
     "Command And Control,Exfiltration,Lateral Movement", "T1090 - ProxyT1071 - Application Layer Protocol",
     "Verified data from past two months and no results found.", "Enabled", "4/28/2026"),
    ("ACME_Custom_Exploitation of specific servers or services especially web servers and databases",
     "Detects potential exploitation attempts on web servers or databases by monitoring suspicious child processes spawned by web server parent processes.",
     "DeviceProcessEvents", "Scheduled", "Qatar Framework", "High",
     'DeviceProcessEvents | where InitiatingProcessFileName in~ ("w3wp.exe","httpd.exe","nginx.exe","tomcat.exe")',
     "Execution, Persistence", "T1190 - Exploit Public-Facing ApplicationT1505 - Server Software Component",
     "Verified data from past two months and no results found.", "Enabled", "9/12/2026"),
    ("ACME_Custom_DLP policy (Printing) matched",
     "Alert generated upon a DLP policy match involving the printing of a document classified under C3/C4.",
     "CloudAppEvents", "Scheduled", "Customer Specific", "High",
     'CloudAppEvents | where TimeGenerated > ago(2h) | where tostring(RawEventData.Source) == "Office 365 Security & Compliance"',
     "Exfiltration", "T1052 - Exfiltration Over Physical Medium",
     "Verified data from past two months and no results found.", "Enabled", ""),
    ("Insider Risk_High User Security Incidents Correlation",
     "Joins SecurityAlerts to SecurityIncidents to associate Security Alerts and Incidents with user accounts.",
     "Microsoft Defender for Cloud Apps, Microsoft Defender for Endpoint", "Scheduled", "Customer Specific", "High",
     'let PreviousIncidents = SecurityIncident | summarize hint.strategy = shuffle arg_max(LastModifiedTime, *) by IncidentNumber',
     "Initial Access", "T1078 - Valid Accounts",
     "Verified data from past two months and no results found.", "Enabled", ""),
    ("ACME_Custom_Potential mass phishing attack",
     "Triggered when multiple users receive suspicious or similar phishing-related emails within a short time window, indicating a potential mass phishing attack.",
     "EmailEvents", "Scheduled", "Customer Specific", "High",
     'EmailEvents | where DeliveryAction == "Delivered" | where ThreatTypes has_any ("Malware","Phish")',
     "Initial Access", "T1566 - Phishing",
     "Verified data from past two months and no results found.", "Enabled", "1/2/2026"),
    ("ACME_Custom_Windows-On Target Recon For Password With Builtin Windows Tools",
     "Triggers when a process (vssadmin.exe) is executed with command-line arguments used to list shadow copies on a Windows system.",
     "SecurityEvent", "Scheduled", "Custom COE", "High",
     'SecurityEvent | where EventID == 4688 | where NewProcessName endswith @"\\vssadmin.exe" | where CommandLine matches regex "list shadows"',
     "Credential Access", "T1003 - OS Credential Dumping",
     "Verified data from past two months and no results found.", "Enabled", "3/17/2026"),
    ("ACME_Custom_Azure WAF Recon Detection",
     "Detects potential massive web recon/scanning against Azure Application Gateway WAF by identifying sources generating high volumes of requests matching XSS, traversal, SQLi rules.",
     "AzureWaf", "Scheduled", "Qatar Framework", "High",
     'AzureDiagnostics | where Category == "ApplicationGatewayFirewallLog" | where action_s in ("Blocked","Matched")',
     "Reconnaissance", "T1595 - Active Scanning",
     "Verified data from past two months and no results found.", "Enabled", "3/15/2026"),
    ("ACME_Custom_UAC-0125 Campaign TTP Installation",
     "Detects installation of Tor in an usual directory as observed in a UAC-0125 campaign using a trojanized Army installer.",
     "DeviceProcessEvents", "Scheduled", "Custom Sigma Rule", "High",
     'DeviceProcessEvents | where ActionType == "ProcessCreated" | where ProcessCommandLine has_all (@"C:\\ProgramData\\OneDrive", "tor.exe")',
     "Command And Control,Persistence", "T1090 - ProxyT1573 - Encrypted ChannelT1543 - Create or Modify System Process",
     "Verified data from past 15 Minutes and no result found.", "Enabled", "10/3/2026"),
    ("ACME_Custom_ZOV Wiper Shutdown Command Execution",
     "Detects execution of a command line associated with Sandworm's ZOV wiper that shuts down the system after wiping files.",
     "DeviceProcessEvents", "Scheduled", "Custom Sigma Rule", "High",
     'DeviceProcessEvents | where ActionType == "ProcessCreated" | where ProcessCommandLine endswith "time /t & ver & rmdir C:\\ /s /q"',
     "Execution, Impact", "T1059 - Command and Scripting InterpreterT1485 - Data Destruction T1529 - System Shutdown/Reboot",
     "Verified data from past 15 Minutes and no result found.", "Enabled", "10/3/2026"),
    ("ACME_Custom_MAL Clop Ransomware File Create",
     "Detects file extensions appended to files encrypted by Clop and the filenames of ransom notes created by Clop.",
     "DeviceFileEvents", "Scheduled", "Custom Sigma Rule", "High",
     'DeviceFileEvents | where ActionType == "FileCreated" | where FileName has_any (".C_L_O_P","\\!_READ_ME.RTF")',
     "Impact", "T1486 - Data Encrypted for Impact",
     "Verified data from past 15 Minutes and no result found.", "Enabled", "9/3/2026"),
    ("ACME_Custom_macOS Login Keychain Database Copy to Temporary Directory",
     "Detects attempts to copy the macOS login.keychain-db, and stage the file under /tmp, which is a common precursor to credential collection.",
     "DeviceFileEvents", "Scheduled", "Custom Sigma Rule", "High",
     'let MacOSDevice = DeviceInfo | where TimeGenerated > ago(30d) | where OSPlatform in ("macOS") | distinct DeviceId',
     "Credential Access", "T1555 - Credentials from Password Stores",
     "Verified data from past 15 Minutes and no result found.", "Enabled", "9/3/2026"),
    ("New EXE deployed via Default Domain or Default Domain Controller Policies",
     "Highlights executables deployed to hosts via either the Default Domain or Default Domain Controller Policies. These policies apply to all hosts or Domain Controllers.",
     "Windows Security Events via AMA", "Scheduled", "OOB", "High",
     'let known_processes = (SecurityEvent | if adjusting Query Period or Frequency update these | where TimeGenerated between(ago(14d)..ago(1d)))',
     "Execution,Lateral Movement", "T1072 - Software Deployment Tools",
     "Verified data from past two months, and No results found.", "Enabled", "26-Jan-26"),
    ("DEV-0270 New User Creation",
     "The following query tries to detect creation of a new user using a known DEV-0270 username/password schema.",
     "Windows Security Events via AMA", "Scheduled", "OOB", "High",
     'union isfuzzy=true(SecurityEvent | where EventID == 4688 | where CommandLine has_all ("net user","/add")) | parse CommandLine',
     "Persistence", "T1098 - Account Manipulation",
     "Verified data from past two months, and No results found.", "Enabled", "26-Jan-26"),
    ("Exchange OAB Virtual Directory Attribute Containing Potential Webshell",
     "Uses Windows Event ID 5136 to detect potential webshell deployment by exploitation of CVE-2021-27065.",
     "Windows Security Events via AMA", "Scheduled", "OOB", "High",
     'SecurityEvent | // Look for specific Directory Service Changes and parse data | where EventID == 5136 | extend EventData = parse_xml(EventData)',
     "Initial Access", "T1190 - Exploit Public-Facing Application",
     "Verified data from past two months, and No results found.", "Enabled", "26-Jan-26"),
    ("Credential Dumping Tools - File Artifacts",
     "Detects the creation of credential dumping tools file artifacts. Several credential dumping tools export files with hardcoded file names.",
     "Windows Security Events via AMA", "Scheduled", "OOB", "High",
     '// Enter a reference list of malicious file artifacts; let MaliciousFileArtifacts = dynamic(["lsass.dmp","test.pwd","lsremora.dll","lsremora64.dll"]);',
     "Credential Access", "T1003 - OS Credential Dumping",
     "Verified data from past two months, and No results found.", "Enabled", "26-Jan-26"),
    ("Scheduled Task Hide",
     "Detects attempts by malware to hide the scheduled task by deleting the SD (Security Descriptor) value. Removal of SD value results in the scheduled task disappearing.",
     "Windows Security Events via AMA", "Scheduled", "OOB", "High",
     'SecurityEvent | where EventID == 4657 | extend EventData = parse_xml(EventData).EventData.Data',
     "Defense Evasion", "T1562 - Impair Defenses",
     "Verified data from past two months, and No results found.", "Enabled", "26-Jan-26"),
    ("Dumping LSASS Process Into a File",
     "Adversaries may attempt to access credential material stored in the process memory of the Local Security Authority Subsystem Service (LSASS).",
     "Windows Security Events via AMA", "Scheduled", "OOB", "High",
     'SecurityEvent | where EventLog == "Microsoft-Windows-Sysmon/Operational" and EventID == 10 | parse EventData with * \'TargetImage\'',
     "Credential Access", "T1003 - OS Credential Dumping",
     "Verified data from past two months, and No results found.", "Enabled", "26-Jan-26"),
    ("Non Domain Controller Active Directory Replication",
     "Identifies potential attempts by non-computer accounts (non domain controllers) to retrieve/synchronize an active directory object leveraging directory replication services.",
     "Windows Security Events via AMA", "Scheduled", "OOB", "High",
     'SecurityEvent | where EventID == 4662 | where AccessMask == "0x100" | where Properties has_all ("(1131f6ad-9c07-11d1-f79f-00c04fc2dcd2)")',
     "Credential Access", "T1003 - OS Credential Dumping",
     "Verified data from past two months, and No results found.", "Enabled", "26-Jan-26"),
    ("ACME_Custom_azure waf detected",
     "Alerts when Azure Web Application Firewall detects a potential attack and its action is Allowed, indicating a possible WAF bypass or misconfiguration.",
     "Azure Firewall", "Scheduled", "Customer Specific", "High",
     'AzureDiagnostics | where Category == "ApplicationGatewayFirewallLog" | where action_s == "Allowed"',
     "Initial Access", "T1190 - Exploit Public-Facing ApplicationT1199 - Trusted Relationship",
     "Verified data from past two months and no results found.", "Enabled", "1/18/2026"),
    ("ACME_Custom_windows registry changes in short span",
     "Detects rapid Windows registry modifications within a 5-minute window. Such modifications may indicate defense evasion or configuration tampering.",
     "Windows Registry", "Scheduled", "Custom COE", "High",
     'let WindowsDevice = DeviceInfo | where TimeGenerated > ago(14d) | where OSPlatform contains "Windows" | distinct DeviceId',
     "Defense Evasion, Persistence", "T1112 - Modify Registry",
     "Verified data from past two months and no results found.", "Enabled", "1/14/2026"),
    ("ACME_Custom_NAT Correlation External to Internal with different sources",
     "Triggers when external source IP addresses that pass through a Network Address Translation (NAT) mechanism are correlated with internal translated IPs and destinations.",
     "Azure Firewall, Fortigate Firewall, Microsoft Entra ID, SecurityAlert", "Scheduled", "Qatar Framework", "High",
     'let NAT = _Im_NetworkSession | where isnotempty(DstNatIpAddr) | where ipv4_is_private(SrcIpAddr)',
     "Command And Control", "T1090 - Proxy",
     "Verified data from past two months and no results found.", "Enabled", "12/28/2025"),
    ("ACME_Custom_Log Source device down",
     "Triggers whenever any log source device is down from last 1 hours. Detects computers that have not sent Heartbeat within the configured threshold.",
     "Heartbeat", "Scheduled", "Qatar Framework", "High",
     'let Threshold = 1h; Heartbeat | where TimeGenerated > ago(3d) // look back window | summarize LastEventTime = max(TimeGenerated)',
     "Impact", "T0826 - Loss of AvailabilityT1496 - Resource Hijacking",
     "Verified data from past 3 months and no result found.", "Enabled", "12/28/2025"),
    ("ACME_Custom_Detection of DOS against infrastructure",
     "Detects Distributed Denial of Service (DoS) attacks targeting application gateways, backend services, and firewalls by correlating multiple telemetry sources.",
     "Azure Firewall, Fortigate", "Scheduled", "Qatar Framework", "High",
     'union isfuzzy=true(_Im_NetworkSession | where NetworkDirection == "Inbound" | summarize TrafficCount = count())',
     "Impact", "T1499 - Endpoint Denial of Service",
     "Verified data from past one month and no result found.", "Enabled", "9/12/2026"),
    ("ACME_Custom_large or sensitive data copied to removable media",
     "Monitors and correlates file operations involving removable media to identify potential data exfiltration risks.",
     "DeviceFileEvents", "Scheduled", "Qatar Framework", "High",
     'DeviceFileEvents | where ActionType == "FileCopiedToExternalDevice" | extend FileSizeMB = toreal(FileSize) / 1024 / 1024',
     "Exfiltration", "T1052 - Exfiltration Over Physical MediumT1052.001 - Exfiltration over USB",
     "Verified data from past two months and no result found.", "Enabled", "2/12/2026"),
    ("ACME_Custom_Identify successful access after failed access attempts to sensitive data",
     "Detects scenarios where a user first fails to access a sensitivity-labeled SharePoint/OneDrive item and then successfully accesses the same item within a short interval.",
     "AzureActivity", "Scheduled", "Qatar Framework", "High",
     'let SensitiveAssets = _GetWatchlist("SensitiveAssets"); let SuccessAccess = AzureActivity | where TimeGenerated >= ago(1d)',
     "Initial Access,Credential Access,Defense Evasion", "T1078 - Valid AccountsT1110 - Brute Force",
     "Verified data from past two months and no result found.", "Enabled", "3/12/2026"),
    ("ACME_Custom_Users trying to access Databases or database tables they don't have access to",
     "Identifies users attempting to access database objects or change permissions without having the required access rights.",
     "AzureDiagnostics", "Scheduled", "Qatar Framework", "High",
     'let threshold = 5; // Minimum failed attempts in time window; AzureDiagnostics | where Category == "SQLSecurityAuditEvents"',
     "Credential Access", "T1078 - Valid AccountsT1110 - Brute Force",
     "Verified data from past two months and no result found.", "Enabled", "9/12/2026"),
    ("ACME_Custom_Unauthorized use of VPN account and remote access to sensitive data",
     "Detects unauthorized access to sensitive resources following a VPN login flagged as risky. Correlates successful VPN sign-ins marked as atRisk with subsequent access.",
     "Active Directory /Microsoft Entra ID", "Scheduled", "Qatar Framework", "High",
     '// Step 1: Identify unusual VPN sign-ins; let vpn_logons = SigninLogs | where AppDisplayName == "VPN" or ResourceDisplayName has "VPN"',
     "Persistence,Privilege Escalation", "T1098 - Account ManipulationT1078 - Valid Accounts",
     "Verified data from past two months and no result found.", "Enabled", "3/12/2026"),
    ("ACME_Custom_User Behaviour monitoring, such as a normal user trying to login to a network device",
     "Identifies potential misuse of privileges or policy violations by monitoring situations where a non-administrative user account successfully logs on to a network device.",
     "CloudAppEvents, Office 365, Windows Server, Windows Device", "Scheduled", "Qatar Framework", "High",
     'let AdminGroups = dynamic(["Domain Admins","Enterprise Admins","Administrators","Network Admins"]);',
     "Privilege Escalation,Lateral Movement", "T1078 - Valid AccountsT1548 - Abuse Elevation Control Mechanism",
     "Verified data from past two months and no result found.", "Enabled", "2/12/2026"),
    ("ACME_Custom_Suspicious admin activity such as logging onto many different devices",
     "Detects when an administrator account logs onto an unusually high number of devices within a short window, which may indicate credential misuse or lateral movement.",
     "DeviceNetworkEvents, DeviceInfo, DeviceProcessEvents, SecurityAlert, ThreatIntelligence", "Scheduled", "Qatar Framework", "High",
     'let TimeWindow = 30m; // Detection window; let BaselineDays = 14d; // Historical baseline',
     "Initial Access,Persistence,Lateral Movement,Discovery", "T0886 - Remote ServicesT1078 - Valid AccountsT1021 - Remote Services",
     "Verified data from past two months and no result found.", "Enabled", "2/12/2026"),
    ("MosaicLoader",
     "Query finds Malware Hides Itself Among Windows Defender Exclusions to Evade Detection.",
     "Microsoft Defender for XDR", "Scheduled", "OOB", "High",
     'DeviceRegistryEvents | where (ActionType == "RegistryValueSet") and (RegistryKey startswith @"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Defender\\Exclusions")',
     "Defense Evasion", "T1562 - Impair Defenses",
     "Verified data from past two months and no result found.", "Enabled", "1/27/2026"),
    ("Potential Ransomware activity related to Cobalt Strike",
     "Searches for alerts related to suspected ransomware and Cobalt Strike activity, a tool used in numerous ransomware campaigns.",
     "Microsoft Defender XDRDeviceLogonEventsAlertInfoAlertEvidence", "Scheduled", "OOB", "High",
     '// Look for sc.exe disabling servicesAlertInfo // Attempts to clear security event logs',
     "Execution,Persistence,Defense Evasion,Impact", "T1059 - Command and Scripting InterpreterT1070 - Indicator RemovalT1486 - Data Encrypted for Impact",
     "Verified data from past two months and no result found.", "Enabled", "29-Nov-25"),
    ("Regsvr32 Rundll32 Image Loads Abnormal Extension",
     "Query is for regsvr32.exe or rundll32.exe loading DLL images with other extensions than .dll. Joins the data to public network events.",
     "Microsoft Defender XDRDeviceNetworkEventsDeviceProcessEvents", "Scheduled", "OOB", "High",
     'DeviceImageLoadEvents | where InitiatingProcessFileName has_any ("rundll32.exe","regsvr32.exe")',
     "Defense Evasion", "T1218 - System Binary Proxy ExecutionT1218.010 - Regsvr32T1218.011 - Rundll32",
     "Verified data from past two months and no result found.", "Enabled", "29-Nov-25"),
    ("Remote File Creation with PsExec",
     "Originally published in the threat analytics report, Ryuk ransomware. There is also a related blog. Ryuk is a human-operated ransomware.",
     "Microsoft Defender XDRDeviceFileEvents", "Scheduled", "OOB", "High",
     '// Find PsExec creating multiple files on remote machines in a 10-minute window; DeviceFileEvents | // Looking for PsExec by accepteula',
     "Lateral Movement", "T1570 - Lateral Tool Transfer",
     "Verified data from past two months and no result found.", "Enabled", "29-Nov-25"),
    ("Service Accounts Performing Remote PS",
     "The purpose behind this detection is to find service accounts that are performing remote powershell sessions.",
     "Microsoft Defender XDRDeviceProcessEventsDeviceLogonEvents", "Scheduled", "OOB", "High",
     'let InteractiveTypes = pack_array( // Declare Interactive logon type names "Interactive", "CachedInteractive", "Unlock");',
     "Lateral Movement", "T1210 - Exploitation of Remote Services",
     "Verified data from past two months and no result found.", "Enabled", "29-Nov-25"),
    ("SUNBURST and SUPERNOVA backdoor hashes",
     "Identifies SolarWinds SUNBURST and SUPERNOVA backdoor file hash IOCs in DeviceFileEvents.",
     "Microsoft Defender XDRDeviceFileEvents", "Scheduled", "OOB", "High",
     'let SunburstMD5 = dynamic(["b91ce2fa41029f6955bff20079466448","02af7cec58b9a5da1c5a3152a0ae659d"]);',
     "Execution,Persistence,Initial Access", "T1059 - Command and Scripting InterpreterT1546 - Event Triggered Execution",
     "Verified data from past two months and no result found.", "Enabled", "29-Nov-25"),
    ("TEARDROP memory-only dropper",
     "Identifies SolarWinds TEARDROP memory-only IOCs in Window's defender Exploit Guard activity.",
     "Microsoft Defender XDRDeviceEvents", "Scheduled", "OOB", "High",
     'DeviceEvents | where ActionType has "ExploitGuardNonMicrosoftSignedBlocked" | where InitiatingProcessFileName has "svchost.exe"',
     "Execution,Persistence,Defense Evasion", "T1059 - Command and Scripting InterpreterT1543 - Create or Modify System Process",
     "Verified data from past two months and no result found.", "Enabled", "29-Nov-25"),
    ("Unusual Volume of file deletion by users",
     "Looks for users performing file deletion activities. Spikes in file deletion observed from risky sign-ins are flagged here. Applies to SharePoint and OneDrive.",
     "Microsoft Defender XDRCloudAppEvents", "Scheduled", "OOB", "High",
     'let relevantOperations = pack_array("FileDeleted","FileRecycled","FileDeletedFirstStageRecycleBin","FileDeletedSecondStageRecycleBin");',
     "Impact", "T1485 - Data Destruction",
     "Verified data from past two months and no result found.", "Enabled", "29-Nov-25"),
    ("Authentication Methods Changed for Privileged Account",
     "Identifies authentication methods being changed for a privileged account. This could be an indication of an attacker adding an auth method to the account so they can have continued access.",
     "Microsoft Entra ID ProtectionSecurityAlert (IPC)", "Scheduled", "OOB", "High",
     'let queryperiod = 14d; let queryfrequency = 2h; let security_info_actions = dynamic(["User registered security info"]);',
     "Persistence", "T1098 - Account Manipulation",
     "Verified data from past two months and no result found.", "Enabled", "24-Nov-25"),
    ("MFA Spamming followed by Successful login",
     "Identifies MFA Spamming followed by Successful login and by a successful authentication within a given time window. Default Failure count is 10 and 1 successful login with 10 min.",
     "Microsoft Entra IDSigninLogs", "Scheduled", "OOB", "High",
     '// Filter for sign-in logs ingested within the last day; SigninLogs | where TimeGenerated > ago(1d)',
     "Credential Access", "T1621 - Multi-Factor Authentication Request Generation",
     "Verified data from past two months and no result found.", "Enabled", "24-Nov-25"),
    ("Bulk Changes to Privileged Account Permissions",
     "Identifies when changes to multiple users permissions are changed at once. Investigate immediately if not a planned change.",
     "Microsoft Entra IDAuditLogs", "Scheduled", "OOB", "High",
     'let AdminRecords = AuditLogs | where Category == "RoleManagement" | where ActivityDisplayName has_any ("Add eligible member")',
     "Privilege Escalation", "T1098 - Account Manipulation",
     "Verified data from past two months and no result found.", "Enabled", "24-Nov-25"),
    ("Azure RBAC (Elevate Access)",
     "Detects when a Global Administrator elevates access to all subscriptions and management groups in a tenant.",
     "Microsoft Entra IDAuditLogs", "Scheduled", "OOB", "High",
     'AuditLogs | where Category == "AzureRBACRoleManagementElevateAccess" | where ActivityDisplayName has "Assign"',
     "Privilege Escalation", "T1078 - Valid AccountsT1078.004 - Cloud Accounts",
     "Verified data from past two months and no result found.", "Enabled", "24-Nov-25"),
    ("ACME_Custom_Windows-QAKBOT Suspicious Scheduled Tasks",
     "Identifies suspicious scheduled task commands of QAKBOT being created.",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'SecurityEvent | where EventID == 4688 | where CommandLine matches regex @"schtasks.*/create.*/tn"',
     "Persistence,Execution", "T1053 - Scheduled Task/JobT1053.005 - Scheduled Task",
     "Validate data from past 1 Hours and no result found.", "Enabled", "3/17/2026"),
    ("ACME_Custom_Windows-Potential DLL Search order Hijacking",
     "Detects possible DLL search order hijacking when a DLL is copied to or from the system root directories or another directory.",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'SecurityEvent | where EventID == 4688 | where CommandLine matches regex @"copy.*\\.dll"',
     "Persistence, Defense Evasion", "T1574 - Hijack Execution Flow",
     "Validate data from past 1 Hours and no result found.", "Enabled", "3/17/2026"),
    ("ACME_Custom_Windows-Suspicious Use of Windows Admin Shares",
     "Windows Admin Shares are hidden administrative network shares (such as ADMIN$, C$, and IPC$) that are accessible only to users with administrative privileges.",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'let adminShareAccesses = SecurityEvent | where EventID == 5140 | extend ShareName = extract(@"<ShareName>(.*?)</ShareName>", 1, EventData)',
     "Lateral Movement,Execution", "T1021 - Remote ServicesT1021.002 - SMB/Windows Admin Shares",
     "Verified data from past two months and no result found.", "Enabled", "3/3/2026"),
    ("ACME_Custom_Windows-Harvesting Credentials from Windows Credential Manager",
     "Adversaries can use the vaultcmd.exe utility to list the credentials that were saved in the Credential Vault in preparation of harvesting them to use during their operations.",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'SecurityEvent | where EventID == 4688 | where NewProcessName endswith @"\\vaultcmd.exe" or NewProcessName endswith @"\\vaultcmd"',
     "Reconnaissance,Credential Access", "T1589 - Gather Victim Identity InformationT1589.001 - Credentials",
     "Verified data from past two months and no result found.", "Enabled", "2/26/2026"),
    ("ACME_Custom_Syslog-Reverse Shell Indicator",
     "Detects a reverse shell contacting to a remote IP address.",
     "Syslog", "Scheduled", "Custom COE", "Medium",
     'Syslog | where SyslogMessage startswith "type=EXECVE" | where SyslogMessage contains "bash -i"',
     "Execution", "T1059 - Command and Scripting Interpreter",
     "Verified data from past 24 Hours and no result found.", "Enabled", "8/2/2026"),
    ("ACME_Custom_Syslog-Potential Data Exfiltration via SFTP",
     "Attackers may use SFTP to exfiltrate sensitive data from compromised hosts. This technique leverages a legitimate protocol to bypass detection by blending with normal admin traffic.",
     "Syslog", "Scheduled", "Custom COE", "Medium",
     'let threshold = 50; Syslog | where ProcessName has "sftp" and SyslogMessage has "bytes read"',
     "Exfiltration", "T1048 - Exfiltration Over Alternative Protocol",
     "Verified data from past 24 Hours and no result found.", "Enabled", "8/2/2026"),
    ("RecordedFuture Threat Hunting IP All Actors",
     "Recorded Future Threat Hunting IP correlation for all actors.",
     "Recorded Future", "Scheduled", "OOB", "Medium",
     'let ioc_lookBack = 1d; // The source table (imFileEvent) is a ASIM parser table, but can be replaced by any infrastructure table',
     "Command And Control", "T1071 - Application Layer Protocol",
     "Verified data from past two months, and No results found.", "Enabled", ""),
    ("ACME_Custom-AMA Syslog Server Heartbeat Monitoring",
     "Monitors heartbeat status of AMA Syslog Server (acme-secama01) and generates alerts when the server stops reporting for more than 15 minutes.",
     "Syslog", "Scheduled", "Server Monitoring", "High",
     'let TimeThreshold = 15m; Heartbeat | where Computer =~ "acme-secama01" | summarize LastHeartbeat = max(TimeGenerated) by Computer',
     "Impact (TA0040)", "T1499 - Endpoint Denial of Service",
     "Analytics rule successfully validated and deployed.", "Enabled", "5-Jul-26"),
    ("ACME_Custom-AMA Log Ingestion Monitoring",
     "Detects log ingestion outages from the AMA Collector when no logs are received in Microsoft Sentinel for more than 15 minutes, even though the AMA Collector is running.",
     "CommonSecurityLog", "Scheduled", "Custom Detection", "High",
     'let Threshold = 15m; CommonSecurityLog | where CollectorHostName =~ "acme-secama01" | summarize LastLogReceived = max(TimeGenerated)',
     "Impact (T1489), Defence Evasion", "T1489 - Service Stop",
     "Analytics rule successfully validated and deployed.", "Enabled", "7-Jul-26"),
    ("ACME_Custom_QSTP-FW6_Port_Scan_Detection_Medium",
     "Identifies port scanning activity by tracking multiple connection attempts across ports.",
     "CommonSecurityLog", "Detection", "Scheduled", "High",
     'let FW6_BASE = CommonSecurityLog | where Computer == "QSTP-FW6" | extend SubType = extract(@"subtype=([^;]+)", 1, AdditionalExtensions)',
     "Reconnaissance", "T1046 - Network Service Discovery",
     "Validated", "Enabled", "6-Jul-26"),
    ("ACME_Custom_QSTP-FW6_Suspicious_Traffic_TOR_Medium",
     "Detects traffic communication with TOR nodes indicating anonymized or potentially malicious activity.",
     "CommonSecurityLog", "Detection", "Scheduled", "High",
     'let FW6_BASE = CommonSecurityLog | where Computer == "QSTP-FW6" | where DestinationIP in (TorExitNodes)',
     "Command and Control", "T1090 - Proxy",
     "Validated", "Enabled", "6-Jul-26"),
    ("ACME_Custom_DLP – Email Exfiltration",
     "Detects high volume email activity indicating potential data exfiltration over email.",
     "OfficeActivity", "Data Exfiltration", "Scheduled", "High",
     'EmailCount > 10',
     "Exfiltration", "T1048 - Exfiltration Over Alternative Protocol",
     "Validated", "Enabled", "18-Jun-26"),
    ("ACME_Custom_DLP – Email Suspicious Activity",
     "Detects abnormal internal spike in email volume.",
     "OfficeActivity", "Insider Risk", "Scheduled", "Medium",
     'EmailCount > threshold',
     "Collection", "T1114 - Email Collection",
     "Validated", "Enabled", "18-Jun-26"),
    ("ACME_Custom_DLP policy (Printing)",
     "Detects printing activity flagged by the DLP policy.",
     "CloudAppEvents", "Data Exfiltration", "Scheduled", "Informational",
     'Printing events',
     "Collection", "T1052 - Exfiltration Over Physical Medium",
     "Validated", "Enabled", "18-Jun-26"),
    ("ACME_Custom_Windows-Suspicious Ntdsutil Activity via Command Line",
     "NTDSUTIL allows an adversary to create copies of Ntds.dit (active directory database).",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'SecurityEvent | where EventID == 4688 | where NewProcessName endswith @"\\ntdsutil.exe"',
     "Credential Access", "T1003 - OS Credential DumpingT1003.003 - NTDS",
     "Verified data from past two months and no result found.", "Enabled", "2/24/2026"),
    ("ACME_Custom_Windows-Kerberos Enumeration Using LDAP Query",
     "Detects for suspicious Kerberos enumeration LDAP query.",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'SecurityEvent | where TimeGenerated > ago(5m) | where EventID == 4662 | where Properties has "servicePrincipalName"',
     "Credential Access", "T1558 - Steal or Forge Kerberos TicketsT1558.003 - Kerberoasting",
     "Verified data from past two months and no result found.", "Enabled", "8/2/2026"),
    ("ACME_Custom_Windows-Brute Force Attempt to Multiple Users",
     "Detects failures on 100 users from same host and user.",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'SecurityEvent | where TimeGenerated > ago(5m) | where EventID == 4625 | summarize FailureCount = count() by IpAddress',
     "Credential Access", "T1110 - Brute ForceT1110.003 - Password Spraying",
     "Verified data from past two months and no result found.", "Enabled", "8/2/2026"),
    ("ACME_Custom_Windows-Masqueraded Process Name Anomalies",
     "Attackers can masquerade the commonly used processes.",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'SecurityEvent | where EventID == 4688 | where NewProcessName endswith "lsass.exe" and NewProcessName !startswith @"C:\\Windows\\System32"',
     "Defense Evasion", "T1036 - MasqueradingT1055 - Process Injection",
     "Verified data from past two months and no result found.", "Enabled", "8/2/2026"),
    ("ACME_Custom_Windows-HTML Smuggling Detection",
     "Detects HTML Execution by Browsers and then Detection of File Download within 1 min.",
     "SecurityEvent", "Scheduled", "Custom COE", "Medium",
     'SecurityEvent | where EventID == 4688 | where NewProcessName has_any ("chrome.exe","msedge.exe") | where CommandLine has ".html"',
     "Defense Evasion, Initial Access", "T1027 - Obfuscated Files or InformationT1566 - Phishing",
     "Verified data from past two months and no result found.", "Enabled", "5/2/2026"),
    ("ACME_Custom_Cyberarc-Backup Account Suspicious Logon",
     "Rule created to monitor the usage of account 'Backup' in unusual hours.",
     "CyberArc_CL", "Scheduled", "Custom COE", "Medium",
     'let excludedhours = dynamic([23, 00, 01]); CyberArk_CL | where act == "Logon" | where user == "Backup"',
     "Persistence", "T1078 - Valid AccountsT1053 - Scheduled Task/Job",
     "Verified data from past 24 Hours and no result found.", "Enabled", ""),
    ("ACME_Custom_ICS-Unauthorized change to control logic on PLC",
     "Detects engineering-workstation writes to PLC control logic outside approved maintenance windows on the OT network.",
     "OT Telemetry (Claroty)", "Scheduled", "Custom COE", "High",
     'ClarotyEvents_CL | where EventType == "ProgramDownload" | where TimeGenerated !between (maintenanceStart .. maintenanceEnd)',
     "Impair Process Control", "T0836 - Modify Parameter",
     "Verified data from past two months and no result found.", "Enabled", "6/2/2026"),
    ("ACME_Custom_ICS-Internet accessible OT device detected",
     "Flags OT devices reachable from public internet addresses, correlating firewall logs with the OT asset inventory.",
     "OT Telemetry (Claroty), Fortinet", "Scheduled", "Custom COE", "High",
     'CommonSecurityLog | where DestinationIP in (OTAssets) | where ipv4_is_private(SourceIP) == false',
     "Initial Access", "T0883 - Internet Accessible Device",
     "Verified data from past two months and 2 result found.", "Enabled", "6/2/2026"),
    ("ACME_Custom_Mobile-Managed device compliance drop",
     "Detects managed mobile devices falling out of Intune compliance, which removes conditional-access protection from corporate data.",
     "Microsoft Intune", "Scheduled", "Custom COE", "Medium",
     'IntuneDeviceComplianceOrg | where ComplianceState == "NonCompliant" | summarize by DeviceName, UserPrincipalName',
     "Defense Evasion", "T1629 - Impair Defenses",
     "Verified data from past two months and 4 result found.", "Enabled", "6/2/2026"),
    ("ACME_Custom_Legacy rule pending retirement",
     "Legacy correlation kept for reference; superseded by the ASIM network-session rules and disabled in production.",
     "Syslog", "Scheduled", "Custom", "Low",
     'Syslog | where SyslogMessage contains "legacy-pattern"',
     "Defense Evasion", "T1562.001 - Disable or Modify Tools",
     "Superseded — retained for audit history.", "Disabled", "12/1/2025"),
    ("ACME_Custom_Unmapped operational health check",
     "Operational monitoring rule with no ATT&CK mapping — tracks SIEM connector health only.",
     "Heartbeat", "Monitoring", "Custom", "Informational",
     'Heartbeat | summarize LastCall = max(TimeGenerated) by Computer',
     "NA", "NA",
     "Validated", "Enabled", "6/2/2026"),
]

# --------------------------------------------------------------------------
# 2. Environment workbook — from the device-technology inventory screenshots
# --------------------------------------------------------------------------
ASSETS = [
    # (entry, present?) — mirrors "Device Technology / Device Vendor" rows
    ("Windows Server 2022 (IT Infrastructure, 346 hosts)", "Yes"),
    ("Windows Server 2019 domain controllers", "Yes"),
    ("Linux (RHEL 226, OEL, CentOS, SUSE — 1259 hosts)", "Yes"),
    ("Red Hat Enterprise Linux 8.7 / 9.2", "Yes"),
    ("VMware ESXi estate (873 hosts, Telco)", "Yes"),
    ("Azure Cloud subscriptions (321 resources)", "Yes"),
    ("Azure VM / Azure AKS / Kubernetes nodes", "Yes"),
    ("Azure Storage, Azure Key Vault, Azure PostgreSQL", "Yes"),
    ("Microsoft 365 (Exchange Online, SharePoint, OneDrive, Teams)", "Yes"),
    ("Microsoft Entra ID (identity provider)", "Yes"),
    ("Oracle Cloud Infrastructure (via Codeless Connector)", "Yes"),
    ("Cisco Nexus / Cisco NCS 5700 switches", "Yes"),
    ("Fortinet FortiGate firewalls (IP Network, 36)", "Yes"),
    ("Palo Alto Cortex XDR protected endpoints", "Yes"),
    ("Nokia / Huawei telco network elements (1799)", "Yes"),
    ("Juniper routers (Telco)", "Yes"),
    ("F5 load balancers", "Yes"),
    ("Infoblox DNS appliances", "Yes"),
    ("Aruba wireless controllers (Office IT)", "Yes"),
    ("IOT Platform devices (105)", "Yes"),
    ("OT/SCADA PLC segment (Access Operations)", "Yes"),
    ("Managed mobile fleet via Microsoft Intune MDM", "Yes"),
    ("Android corporate handsets (Intune enrolled)", "Yes"),
    ("iOS / iPadOS corporate devices (Intune enrolled)", "Yes"),
    ("macOS engineering laptops", "Yes"),
    ("Rubrik backup appliances", "Yes"),
    ("Photon OS appliances", "Yes"),
    ("Mainframe z/OS billing platform", "Yes"),
    ("Legacy Solaris estate (decommissioned Q1)", "No"),
    ("AWS EC2 workloads (migration cancelled)", "No"),
]

LOG_SOURCES = [
    ("Windows Security Events via AMA", "Yes"),
    ("Microsoft Defender XDR (DeviceProcessEvents, DeviceFileEvents, DeviceNetworkEvents)", "Yes"),
    ("Microsoft Entra ID SigninLogs", "Yes"),
    ("Microsoft Entra ID AuditLogs", "Yes"),
    ("Azure Activity", "Yes"),
    ("AzureDiagnostics (Application Gateway WAF, SQL audit)", "Yes"),
    ("Azure Key Vault diagnostics", "Yes"),
    ("Azure Firewall", "Yes"),
    ("CommonSecurityLog (CEF — Fortinet, Palo Alto)", "Yes"),
    ("Syslog via AMA (Linux estate)", "Yes"),
    ("Microsoft 365 OfficeActivity (Exchange, SharePoint, Teams)", "Yes"),
    ("CloudAppEvents (Defender for Cloud Apps)", "Yes"),
    ("EmailEvents / EmailAttachmentInfo (Defender for Office 365)", "Yes"),
    ("Microsoft Purview Information Protection", "Yes"),
    ("PaloAltoCortexXDR_Incidents_CL", "Yes"),
    ("CyberArk_CL (PAM vault activity)", "Yes"),
    ("Heartbeat (agent health)", "Yes"),
    ("ThreatIntelligenceIndicator (TI feeds)", "Yes"),
    ("Recorded Future TPI", "Yes"),
    ("NetScout / Arbor DDoS telemetry", "Yes"),
    ("Fortinet VPN (FortiAuthenticator)", "Yes"),
    ("Microsoft Intune device compliance", "Yes"),
    ("Claroty OT telemetry", "Yes"),
    ("Zeek network sensor (pilot only, not onboarded)", "No"),
]

TOOLING = [
    ("Microsoft Sentinel (SIEM)", "Yes"),
    ("Microsoft Defender for Endpoint", "Yes"),
    ("Microsoft Defender for Identity", "Yes"),
    ("Microsoft Defender for Office 365", "Yes"),
    ("Microsoft Defender for Cloud Apps", "Yes"),
    ("Microsoft Defender Threat Intelligence", "Yes"),
    ("Microsoft Purview Information Protection / DLP", "Yes"),
    ("Microsoft Entra ID Protection", "Yes"),
    ("Palo Alto Cortex XDR", "Yes"),
    ("CyberArk PAM", "Yes"),
    ("Fortinet FortiGate / FortiAuthenticator", "Yes"),
    ("Azure Web Application Firewall", "Yes"),
    ("Recorded Future threat intelligence", "Yes"),
    ("Microsoft Intune (MDM/EMM)", "Yes"),
    ("Claroty OT security monitoring", "Yes"),
    ("Rubrik backup and recovery", "Yes"),
]

CROWN_JEWELS = [
    ("Telco subscriber billing platform", "Yes"),
    ("Microsoft Entra ID tenant (identity)", "Yes"),
    ("CyberArk credential vault", "Yes"),
    ("Azure production subscription", "Yes"),
    ("Customer PII data lake (Azure Storage)", "Yes"),
    ("OT/SCADA process control network", "Yes"),
    ("Microsoft 365 executive mailboxes", "Yes"),
]


def _style(ws, widths, header_fill="C00000"):
    from openpyxl.styles import Border, Side
    thin = Side(style="thin", color="8496AD")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    for cell in ws[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color=header_fill, end_color=header_fill, fill_type="solid")
        cell.alignment = Alignment(vertical="center", wrap_text=True)
        cell.border = border
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = border
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[chr(64 + i) if i <= 26 else "A"].width = w
    ws.freeze_panes = "A2"


def build_use_cases(path: Path) -> int:
    wb = Workbook()
    ws = wb.active
    ws.title = "Consolidated Usecase Tracker"
    ws.append(UC_HEADERS)
    for i, r in enumerate(RULES, start=1):
        ws.append([i, *r])
    _style(ws, [6, 46, 60, 30, 14, 18, 13, 60, 26, 40, 34, 10, 16])
    # A second, ignored sheet — real workbooks have several; the parser must
    # still find the tracker sheet.
    ws2 = wb.create_sheet("MITRE HeatMap")
    ws2.append(["Tactic", "Techniques covered", "Note"])
    ws2.append(["(reference sheet — not parsed)", "", ""])
    wb.save(path)
    return len(RULES)


def build_environment(path: Path) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "Assets"
    ws.append(["Asset", "Present?"])
    for entry, present in ASSETS:
        ws.append([entry, present])
    _style(ws, [58, 12], header_fill="0057B8")

    for title, rows, widths in (
        ("Log Sources", LOG_SOURCES, [64, 12]),
        ("Security Tooling", TOOLING, [48, 12]),
        ("Crown Jewels", CROWN_JEWELS, [46, 12]),
    ):
        ws = wb.create_sheet(title)
        ws.append([title.rstrip("s") if title != "Security Tooling" else "Tool", "Present?"])
        for entry, present in rows:
            ws.append([entry, present])
        _style(ws, widths, header_fill="0057B8")
    wb.save(path)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    uc_path = OUT / "acme_sentinel_usecases.xlsx"
    env_path = OUT / "acme_environment.xlsx"
    count = build_use_cases(uc_path)
    build_environment(env_path)

    # ---------------- validation: real parsers + pinned dataset ------------
    parsed = ingest.parse_use_case_file(uc_path.read_bytes(), "xlsx")
    assert parsed["row_count"] == count, f"{parsed['row_count']} != {count}"
    detected = set(parsed["columns"])
    expected = {"name", "tags", "description", "logic", "log_source", "enabled"}
    missing = expected - detected
    assert not missing, f"columns not auto-detected: {missing}"

    index = attack_data.DEFAULT
    statuses: dict = {}
    bad = []
    for row in parsed["rows"]:
        for tag in row["tags"]:
            _, status = index.resolve(tag)
            statuses[status] = statuses.get(status, 0) + 1
            if status in ("unknown", "malformed"):
                bad.append((row["row_ref"], tag))
    assert not bad, f"invalid technique IDs (fix the source rows): {bad}"

    env = ingest.parse_environment_file(env_path.read_bytes(), "xlsx")
    e = env["environment"]
    assert e["inventory_provided"], "Assets sheet not detected"
    assert e["has_ics_assets"], "OT/SCADA row should gate the ICS matrix"
    assert e["has_managed_mobile"], "Intune MDM row should gate the Mobile matrix"
    assert env["log_sources"] and env["tooling"] and env["crown_jewels"]
    skipped = [i["entry"] for i in env["interpretations"]
               if "Present = No" in i["interpretation"]]
    assert len(skipped) == 3, f"expected 3 Present=No skips, got {skipped}"

    tagged = sum(1 for r in parsed["rows"] if r["tags"])
    print(f"OK  {uc_path.name}: {count} rules ({tagged} tagged, {count - tagged} untagged)")
    print(f"    columns auto-detected: {sorted(detected)}")
    print(f"    technique-ID resolution: {statuses}")
    print(f"OK  {env_path.name}: platforms={e['platforms']}")
    print(f"    ICS={e['has_ics_assets']} mobile={e['has_managed_mobile']} "
          f"log_sources={len(env['log_sources'])} tooling={len(env['tooling'])} "
          f"crown_jewels={len(env['crown_jewels'])}")
    print(f"    skipped (Present=No): {skipped}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
