"""Generate apps/web/app/app-theme.css from the design canvas TOKENS.

Single-source rule: colours live once, in docs/design/complete-app-2026-09-12/dc.py
(the design canvas generator). Edit a colour there, re-run

    python scripts/generate_app_theme.py

and both the canvas and the app pick it up. Never hand-edit app-theme.css.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
DESIGN = os.path.join(REPO, "docs", "design", "complete-app-2026-09-12")
OUT = os.path.join(REPO, "apps", "web", "app", "app-theme.css")

sys.path.insert(0, DESIGN)
from dc import TOKENS  # noqa: E402


def hsl(hex_str):
    """'#RRGGBB' -> shadcn triple 'H S% L%' (integers)."""
    h = hex_str.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    mx, mn = max(r, g, b), min(r, g, b)
    l = (mx + mn) / 2
    if mx == mn:
        return "0 0%% %d%%" % round(l * 100)
    d = mx - mn
    s = d / (2 - mx - mn) if l > 0.5 else d / (mx + mn)
    if mx == r:
        hue = ((g - b) / d) % 6
    elif mx == g:
        hue = (b - r) / d + 2
    else:
        hue = (r - g) / d + 4
    return "%d %d%% %d%%" % (round(hue * 60) % 360, round(s * 100), round(l * 100))


# shadcn variables: (css name, token or literal)
SHADCN = [
    ("--background", "paper"), ("--foreground", "ink"),
    ("--card", "card"), ("--card-foreground", "ink"),
    ("--popover", "card"), ("--popover-foreground", "ink"),
    ("--primary", "accent"), ("--primary-foreground", "0 0% 100%"),
    ("--secondary", "ink2"), ("--secondary-foreground", "0 0% 100%"),
    ("--muted", "na"), ("--muted-foreground", "ink2"),
    ("--accent", "accent_soft"), ("--accent-foreground", "ink"),
    ("--destructive", "crit"), ("--destructive-foreground", "0 0% 100%"),
    ("--border", "line"), ("--input", "line2"), ("--ring", "accent"),
]
# semantic variables, raw hex
SEMANTIC = [
    ("--ink-3", "ink3"), ("--line-2", "line2"), ("--accent-soft", "accent_soft"),
    ("--sev-crit", "crit"), ("--sev-crit-soft", "crit_soft"),
    ("--sev-high", "high"), ("--sev-high-soft", "high_soft"),
    ("--sev-med", "med"), ("--sev-med-soft", "med_soft"),
    ("--sev-low", "low"), ("--sev-low-soft", "low_soft"),
    ("--sev-info", "info"), ("--sev-info-soft", "info_soft"),
    ("--ok", "ok"), ("--ok-soft", "ok_soft"),
    ("--violet", "violet"), ("--violet-soft", "violet_soft"),
    ("--na", "na"), ("--amber-bg", "amber_bg"),
]
CONSTANTS = [
    ("--radius", "0.5rem"),
    ("--ease", "cubic-bezier(.22,.61,.36,1)"),
    ("--shadow-card", "0 1px 2px rgba(20,24,31,.05),0 8px 24px -12px rgba(20,24,31,.16)"),
]


def main():
    assert hsl("#FFFFFF") == "0 0% 100%" and hsl("#000000") == "0 0% 0%"
    lines = [
        "/* Generated by scripts/generate_app_theme.py from docs/design/complete-app-2026-09-12/dc.py TOKENS. "
        "Do not edit; re-run the script. */",
        ".app-theme {",
    ]
    for name, tok in SHADCN:
        if tok in TOKENS:
            lines.append("  %s: %s; /* %s %s */" % (name, hsl(TOKENS[tok]), tok, TOKENS[tok]))
        else:
            lines.append("  %s: %s;" % (name, tok))
    for name, tok in SEMANTIC:
        lines.append("  %s: %s;" % (name, TOKENS[tok]))
    for name, val in CONSTANTS:
        lines.append("  %s: %s;" % (name, val))
    lines.append("}")
    lines.append("/* body already painted the :root colours; the app root must repaint from its own variables. */")
    lines.append(".app-theme { background-color: hsl(var(--background)); color: hsl(var(--foreground)); "
                 "-webkit-font-smoothing: antialiased; }")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("%s: %d variables" % (os.path.relpath(OUT, REPO), len(SHADCN) + len(SEMANTIC) + len(CONSTANTS)))


if __name__ == "__main__":
    main()
