"""One-off data migration (Phase A of Document Lifecycle plan, migration 023):
for each org, group existing documents.project_name values, auto-map exact
matches to a new Project row, and flag near-duplicates (case/whitespace/
punctuation variants) into a markdown report for manual merge instead of
auto-merging them. Idempotent: re-running skips project_name values that
already have project_id set.

Usage:
    python scripts/backfill_projects.py
"""

from __future__ import annotations

import asyncio
import re
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import select

from app.db.session import AsyncSessionLocal
from app.models.document import Document
from app.models.project import Project

REPO_ROOT = Path(__file__).resolve().parents[3]
REPORT_PATH = REPO_ROOT / "docs" / "phases" / "summaries" / "PROJECT_MIGRATION_REPORT.md"


def _normalize(name: str) -> str:
    """Case/whitespace/punctuation-insensitive key for near-duplicate grouping."""
    return re.sub(r"[^a-z0-9]+", "", name.lower())


async def backfill() -> None:
    async with AsyncSessionLocal() as db:
        result = await db.execute(
            select(Document).where(
                Document.project_name.isnot(None),
                Document.project_id.is_(None),
                Document.deleted_at.is_(None),
            )
        )
        docs = result.scalars().all()

        by_org: dict = defaultdict(lambda: defaultdict(list))
        for doc in docs:
            by_org[doc.org_id][doc.project_name].append(doc)

        auto_mapped: list[tuple] = []  # (org_id, exact_name, doc_count)
        flagged: list[tuple] = []  # (org_id, normalized_key, [names])

        for org_id, names_to_docs in by_org.items():
            # Group exact names by their normalized key to detect near-dups.
            normalized_groups: dict = defaultdict(list)
            for name in names_to_docs:
                normalized_groups[_normalize(name)].append(name)

            for norm_key, variant_names in normalized_groups.items():
                if len(variant_names) == 1:
                    # Single exact-name group -- auto-map.
                    name = variant_names[0]
                    project = Project(org_id=org_id, name=name)
                    db.add(project)
                    await db.flush()
                    for doc in names_to_docs[name]:
                        doc.project_id = project.project_id
                    auto_mapped.append((org_id, name, len(names_to_docs[name])))
                else:
                    # Multiple distinct spellings collapse to the same
                    # normalized key -- do NOT auto-merge, leave project_id
                    # unset on these documents for a human to decide.
                    flagged.append((org_id, norm_key, variant_names))

        await db.commit()

        already_result = await db.execute(
            select(Project.name, Project.org_id, Document.doc_id).join(
                Document, Document.project_id == Project.project_id
            )
        )
        already_migrated = defaultdict(int)
        for name, org_id, _doc_id in already_result.all():
            already_migrated[(org_id, name)] += 1

        _write_report(auto_mapped, flagged, already_migrated)


def _write_report(auto_mapped: list[tuple], flagged: list[tuple], already_migrated: dict) -> None:
    lines = [
        "# Project Migration Report",
        "",
        f"Generated by `scripts/backfill_projects.py` on "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}.",
        "",
        "## Auto-mapped (exact project_name match within org)",
        "",
    ]
    if auto_mapped:
        lines.append("| org_id | project name | documents |")
        lines.append("|---|---|---|")
        for org_id, name, count in auto_mapped:
            lines.append(f"| {org_id} | {name} | {count} |")
    else:
        lines.append("None.")

    lines += ["", "## Already migrated (from this or a prior run)", ""]
    if already_migrated:
        lines.append("| org_id | project name | documents |")
        lines.append("|---|---|---|")
        for (org_id, name), count in sorted(already_migrated.items(), key=lambda kv: str(kv[0])):
            lines.append(f"| {org_id} | {name} | {count} |")
    else:
        lines.append("None.")

    lines += [
        "",
        "## Flagged for manual review (near-duplicate spellings, NOT auto-merged)",
        "",
        "Documents under these project_name values were left with `project_id`"
        " unset. Pick one canonical name per group and either create the"
        " Project via `POST /api/v1/projects` and link manually, or re-run"
        " this script after renaming the source project_name values to match.",
        "",
    ]
    if flagged:
        for org_id, norm_key, variants in flagged:
            lines.append(f"- org `{org_id}`: {', '.join(repr(v) for v in variants)}")
    else:
        lines.append("None.")
    lines.append("")

    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")

    print(f"Report written to {REPORT_PATH}")


if __name__ == "__main__":
    asyncio.run(backfill())
